//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VixenPlus.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VixenPlus.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About .
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Channels.
        /// </summary>
        public static string AllChannels {
            get {
                return ResourceManager.GetString("AllChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields are required..
        /// </summary>
        public static string AllFieldsRequired {
            get {
                return ResourceManager.GetString("AllFieldsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All supported formats.
        /// </summary>
        public static string AllSupportedFormats {
            get {
                return ResourceManager.GetString("AllSupportedFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will cause all executing timers to stop.
        ///
        ///Do you wish to do this?.
        /// </summary>
        public static string AllTimersWillStop {
            get {
                return ResourceManager.GetString("AllTimersWillStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap arrow_down {
            get {
                object obj = ResourceManager.GetObject("arrow_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap arrow_up {
            get {
                object obj = ResourceManager.GetObject("arrow_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to attach this sequence to the new profile?.
        /// </summary>
        public static string AttachToNewProfile {
            get {
                return ResourceManager.GetString("AttachToNewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap audio_note {
            get {
                object obj = ResourceManager.GetObject("audio_note", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Audio.
        /// </summary>
        public static string AudioButtonAddText {
            get {
                return ResourceManager.GetString("AudioButtonAddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Ball_Green {
            get {
                object obj = ResourceManager.GetObject("Ball_Green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phoenix
        ///Materdaddy
        ///Eagle
        ///Falcon
        ///Keith Tarpley
        ///gdyrdave
        ///ErnieHorning
        ///johnfish211
        ///mkozik1
        ///crazy_carpenter
        ///Rob Anderson
        ///budude
        ///Aurbo99
        ///teberle
        ///.
        /// </summary>
        public static string BetaTesters {
            get {
                return ResourceManager.GetString("BetaTesters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to budude
        ///ErnieHorning
        ///Materdaddy
        ///flashpop
        ///.
        /// </summary>
        public static string Buggos {
            get {
                return ResourceManager.GetString("Buggos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t import channel names when a sequence is attached to a profile..
        /// </summary>
        public static string CantImportChannels {
            get {
                return ResourceManager.GetString("CantImportChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        public static string Channel {
            get {
                return ResourceManager.GetString("Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel output mapping.
        /// </summary>
        public static string ChannelCaption {
            get {
                return ResourceManager.GetString("ChannelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be an equal number of channel names as there are channels.
        /// </summary>
        public static string ChannelCountAndNameInequal {
            get {
                return ResourceManager.GetString("ChannelCountAndNameInequal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The channel count must be 1 or greater.
        /// </summary>
        public static string ChannelCountMinimums {
            get {
                return ResourceManager.GetString("ChannelCountMinimums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel count has been updated..
        /// </summary>
        public static string ChannelCountUpdated {
            get {
                return ResourceManager.GetString("ChannelCountUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel &quot;{0}&quot; cleared of new events..
        /// </summary>
        public static string ChannelEventsClerared {
            get {
                return ResourceManager.GetString("ChannelEventsClerared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel names cannot be blank.
        /// </summary>
        public static string ChannelNameCantBeBlank {
            get {
                return ResourceManager.GetString("ChannelNameCantBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel name import done..
        /// </summary>
        public static string ChannelNameImport {
            get {
                return ResourceManager.GetString("ChannelNameImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel name list exported to.
        /// </summary>
        public static string ChannelNameListExported {
            get {
                return ResourceManager.GetString("ChannelNameListExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Output Mapping.
        /// </summary>
        public static string ChannelOrderDialogText {
            get {
                return ResourceManager.GetString("ChannelOrderDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What would you like to name this channel ordering?.
        /// </summary>
        public static string ChannelOrderingName {
            get {
                return ResourceManager.GetString("ChannelOrderingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channels.
        /// </summary>
        public static string Channels {
            get {
                return ResourceManager.GetString("Channels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel .
        /// </summary>
        public static string ChannelSpace {
            get {
                return ResourceManager.GetString("ChannelSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap choose_speed {
            get {
                object obj = ResourceManager.GetObject("choose_speed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all of the cells in this sequence?.
        /// </summary>
        public static string ClearAllEventsInSequencePrompt {
            get {
                return ResourceManager.GetString("ClearAllEventsInSequencePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color already exists in the list..
        /// </summary>
        public static string ColorAlreadyExists {
            get {
                return ResourceManager.GetString("ColorAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computing waveform, one moment, please..
        /// </summary>
        public static string ComputingWaveform {
            get {
                return ResourceManager.GetString("ComputingWaveform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you really want {0} channels?.
        /// </summary>
        public static string ConfirmChannelCount {
            get {
                return ResourceManager.GetString("ConfirmChannelCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap copy {
            get {
                object obj = ResourceManager.GetObject("copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string CopyText {
            get {
                return ResourceManager.GetString("CopyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countdown....
        /// </summary>
        public static string Countdown {
            get {
                return ResourceManager.GetString("Countdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop ({0}).
        /// </summary>
        public static string CountdownStop {
            get {
                return ResourceManager.GetString("CountdownStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap crosshairs {
            get {
                object obj = ResourceManager.GetObject("crosshairs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap cut {
            get {
                object obj = ResourceManager.GetObject("cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string CutText {
            get {
                return ResourceManager.GetString("CutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dedicated To:.
        /// </summary>
        public static string DedicatedTo {
            get {
                return ResourceManager.GetString("DedicatedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        public static string DeleteChannelConfirmation {
            get {
                return ResourceManager.GetString("DeleteChannelConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete channel order &apos;{0}&apos;?.
        /// </summary>
        public static string DeleteChannelOrder {
            get {
                return ResourceManager.GetString("DeleteChannelOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to detach this sequence from its profile?
        ///
        ///This will not cause anything to be deleted.
        ///Vixen Plus will attempt to reload channel and plugin data from the sequence..
        /// </summary>
        public static string DetachSequenceFromProfile {
            get {
                return ResourceManager.GetString("DetachSequenceFromProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump file written to .
        /// </summary>
        public static string DumpFileWritten {
            get {
                return ResourceManager.GetString("DumpFileWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is missing or does not contain a valid engine.
        /// </summary>
        public static string EngineMissingOrInvalid {
            get {
                return ResourceManager.GetString("EngineMissingOrInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when shutting down the plugin:
        ///.
        /// </summary>
        public static string engineShutDownError {
            get {
                return ResourceManager.GetString("engineShutDownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///Execution has been stopped..
        /// </summary>
        public static string EngineStoppedError {
            get {
                return ResourceManager.GetString("EngineStoppedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin error.
        /// </summary>
        public static string EngineStoppedHeading {
            get {
                return ResourceManager.GetString("EngineStoppedHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error trying to load a scheduled item:
        ///{0}
        ///
        ///The error was:
        ///{1}.
        /// </summary>
        public static string ErrorExecutingTimer {
            get {
                return ResourceManager.GetString("ErrorExecutingTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in file at line {0}:
        ///{1}.
        /// </summary>
        public static string ErrorInCurveFile {
            get {
                return ResourceManager.GetString("ErrorInCurveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading audio:
        ///.
        /// </summary>
        public static string ErrorLoadingAudio {
            get {
                return ResourceManager.GetString("ErrorLoadingAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while loading the file:
        ///.
        /// </summary>
        public static string ErrorLoadingCurveFile {
            get {
                return ResourceManager.GetString("ErrorLoadingCurveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured processing the group file {0}. As a result, one or more groups may not be available. You should check {0} for proper formatting or recreate your groups.
        ///
        ///Press OK to continue or Cancel to quit {1} and log this error to the crash.log..
        /// </summary>
        public static string ErrorLoadingGroup {
            get {
                return ResourceManager.GetString("ErrorLoadingGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were errors when trying to add the following songs:
        ///
        ///.
        /// </summary>
        public static string ErrorsLoadingSongs {
            get {
                return ResourceManager.GetString("ErrorsLoadingSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is not a valid number for the event period length.
        /// </summary>
        public static string EventPeriodInvalid {
            get {
                return ResourceManager.GetString("EventPeriodInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While possible, event periods less than {0}ms are not supported..
        /// </summary>
        public static string EventPeriodTooShort {
            get {
                return ResourceManager.GetString("EventPeriodTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while exporting:
        ///.
        /// </summary>
        public static string ExportError {
            get {
                return ResourceManager.GetString("ExportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify where to export curves.
        /// </summary>
        public static string ExportFile {
            get {
                return ResourceManager.GetString("ExportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export successful..
        /// </summary>
        public static string ExportSuccess {
            get {
                return ResourceManager.GetString("ExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Beta
        /// Bug Exterminators:.
        /// </summary>
        public static string Exterminators {
            get {
                return ResourceManager.GetString("Exterminators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap fade {
            get {
                object obj = ResourceManager.GetObject("fade", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine assembly.
        /// </summary>
        public static string Filter_EngineAssembly {
            get {
                return ResourceManager.GetString("Filter_EngineAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find and Replace.
        /// </summary>
        public static string FindAndReplace {
            get {
                return ResourceManager.GetString("FindAndReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to {0}! Thank you for choosing our program. It looks like this is the first time you have run {0} (or maybe you are setting up a new instance.) {0} needs to know where to store your data, so please choose from the following options, which can be changed in Tools..Preferences later:.
        /// </summary>
        public static string FirstRunPrompt {
            get {
                return ResourceManager.GetString("FirstRunPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will detach the sequence from the profile and bring the profile data into the sequence.
        ///Is this what you want to do?.
        /// </summary>
        public static string FlattendProfileIntoSequence {
            get {
                return ResourceManager.GetString("FlattendProfileIntoSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        public static string FormattedVersion {
            get {
                return ResourceManager.GetString("FormattedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        public static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap gradient_or_ramp {
            get {
                object obj = ResourceManager.GetObject("gradient_or_ramp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Loading Error.
        /// </summary>
        public static string GroupLoadingError {
            get {
                return ResourceManager.GetString("GroupLoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap half_note {
            get {
                object obj = ResourceManager.GetObject("half_note", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A background sequence has been specified, but it does not exist.
        ///This message will show each time you start the application and this situation exists..
        /// </summary>
        public static string Host_BackgroundSequenceName {
            get {
                return ResourceManager.GetString("Host_BackgroundSequenceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is running.
        /// </summary>
        public static string Host_isRunning {
            get {
                return ResourceManager.GetString("Host_isRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio logging is enabled but no log file is specified.
        ///
        ///Audio logging has been turned off..
        /// </summary>
        public static string Host_LogAudioFailed {
            get {
                return ResourceManager.GetString("Host_LogAudioFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem starting the background sequence..
        /// </summary>
        public static string Host_StartingBackgroundSequenceFailed {
            get {
                return ResourceManager.GetString("Host_StartingBackgroundSequenceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a curves file to import.
        /// </summary>
        public static string ImportFile {
            get {
                return ResourceManager.GetString("ImportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sequence does not contain as many channels as the profile you are detaching from.
        ///Do you want to increase the channel count to prevent any possible data loss?.
        /// </summary>
        public static string IncreaseChannelCount {
            get {
                return ResourceManager.GetString("IncreaseChannelCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input is disabled.
        /// </summary>
        public static string InputDisabled {
            get {
                return ResourceManager.GetString("InputDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input is enabled and is mapped to:.
        /// </summary>
        public static string InputEnabled {
            get {
                return ResourceManager.GetString("InputEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserting a new channel cannot be undone
        ///and will cause your undo history to be deleted.  Proceed?.
        /// </summary>
        public static string InsertChannel {
            get {
                return ResourceManager.GetString("InsertChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Channel?.
        /// </summary>
        public static string InsertChannelConfirmation {
            get {
                return ResourceManager.GetString("InsertChannelConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspired By:.
        /// </summary>
        public static string InspiredBy {
            get {
                return ResourceManager.GetString("InspiredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap intensity {
            get {
                object obj = ResourceManager.GetObject("intensity", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What intensity level (0-255)?.
        /// </summary>
        public static string IntensityLevelPrompt {
            get {
                return ResourceManager.GetString("IntensityLevelPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What % intensity (0-100)?.
        /// </summary>
        public static string IntensityPercentPrompt {
            get {
                return ResourceManager.GetString("IntensityPercentPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The interval count is not a valid number.  Do you want to continue?
        ///
        ///If you choose Yes, the narrative will be disabled..
        /// </summary>
        public static string IntervalInvalid {
            get {
                return ResourceManager.GetString("IntervalInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An interval count less than 2 is not usable.  Do you want to continue?
        ///
        ///If you choose Yes, the narrative will be disabled..
        /// </summary>
        public static string IntervalTooSmall {
            get {
                return ResourceManager.GetString("IntervalTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is not a valid number for the channel count.
        /// </summary>
        public static string InvalidChannelCount {
            get {
                return ResourceManager.GetString("InvalidChannelCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid numeric value for the number of channels to add..
        /// </summary>
        public static string InvalidChannelsToAdd {
            get {
                return ResourceManager.GetString("InvalidChannelsToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid number..
        /// </summary>
        public static string InvalidNumber {
            get {
                return ResourceManager.GetString("InvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attemped to save to non-existent file path:
        ///.
        /// </summary>
        public static string InvalidPath {
            get {
                return ResourceManager.GetString("InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid value.
        ///Please select a value between 0 and 100..
        /// </summary>
        public static string InvalidPercentage {
            get {
                return ResourceManager.GetString("InvalidPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set the sequence length.
        ///There is audio associated which would exceed that length..
        /// </summary>
        public static string InvalidSequenceLength {
            get {
                return ResourceManager.GetString("InvalidSequenceLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid time format.
        ///Please use one of the following:
        ///
        ///Seconds
        ///Minutes:Seconds
        ///Seconds.Milliseconds
        ///Minutes:Seconds.Milliseconds.
        /// </summary>
        public static string InvalidTimeFormat {
            get {
                return ResourceManager.GetString("InvalidTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid format for time.
        ///Use one of the following:
        ///
        ///Minutes
        ///Minutes:Seconds
        ///Minutes:Seconds.Milliseconds.
        /// </summary>
        public static string InvalidTimeFormat2 {
            get {
                return ResourceManager.GetString("InvalidTimeFormat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid value.
        ///Please select a value between 0 and 255..
        /// </summary>
        public static string InvalidValue {
            get {
                return ResourceManager.GetString("InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap invert {
            get {
                object obj = ResourceManager.GetObject("invert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap level_Number {
            get {
                object obj = ResourceManager.GetObject("level_Number", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap level_Percent {
            get {
                object obj = ResourceManager.GetObject("level_Percent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap list_add {
            get {
                object obj = ResourceManager.GetObject("list_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap list_remove {
            get {
                object obj = ResourceManager.GetObject("list_remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Routine.
        /// </summary>
        public static string LoadRoutine {
            get {
                return ResourceManager.GetString("LoadRoutine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We hope you&apos;re enjoying using {0}! If you change your directory, {0} will NOT move your data to the new location, you will need to close {0} and then move your files to the new location, so save your open files before using this feature. Please select where you would like your data to be stored now:.
        /// </summary>
        public static string LocationChangePrompt {
            get {
                return ResourceManager.GetString("LocationChangePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing timer for {0} at {1}.
        /// </summary>
        public static string LogExecutingTimer {
            get {
                return ResourceManager.GetString("LogExecutingTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap loop {
            get {
                object obj = ResourceManager.GetObject("loop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///Lutefisk for all!.
        /// </summary>
        public static string Lutefisk {
            get {
                return ResourceManager.GetString("Lutefisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mask {
            get {
                object obj = ResourceManager.GetObject("mask", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum must be less than the maximum..
        /// </summary>
        public static string MinLessThanMax {
            get {
                return ResourceManager.GetString("MinLessThanMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mirror_horz {
            get {
                object obj = ResourceManager.GetObject("mirror_horz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mirror_vert {
            get {
                object obj = ResourceManager.GetObject("mirror_vert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Attribute corrupt or missing in {0} at node {1}.
        /// </summary>
        public static string MissingNameAttribute {
            get {
                return ResourceManager.GetString("MissingNameAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple.
        /// </summary>
        public static string Multiple {
            get {
                return ResourceManager.GetString("Multiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My friends at DIYChristmas.org.
        /// </summary>
        public static string MyFriends {
            get {
                return ResourceManager.GetString("MyFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name for the new profile.
        /// </summary>
        public static string NameNewProfile {
            get {
                return ResourceManager.GetString("NameNewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want to name this profile?.
        /// </summary>
        public static string NameThisProfile {
            get {
                return ResourceManager.GetString("NameThisProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With the new channel count, some channels would refer to outputs that no longer exist.
        ///To keep the sequence valid, channel outputs will have to be reset.
        ///
        ///Do you want to keep the new channel count?.
        /// </summary>
        public static string NewChannelCountPrompt {
            get {
                return ResourceManager.GetString("NewChannelCountPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New order.
        /// </summary>
        public static string NewOrderPrompt {
            get {
                return ResourceManager.GetString("NewOrderPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Profile.
        /// </summary>
        public static string NewProfilePrompt {
            get {
                return ResourceManager.GetString("NewProfilePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap newSequence {
            get {
                object obj = ResourceManager.GetObject("newSequence", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This event sequence does not have audio assigned.
        /// </summary>
        public static string NoAudioAssigned {
            get {
                return ResourceManager.GetString("NoAudioAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no channels to reorder..
        /// </summary>
        public static string NoChannelsToReorder {
            get {
                return ResourceManager.GetString("NoChannelsToReorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected to use a single input to iterate the mapping sets, but have not chosen an input..
        /// </summary>
        public static string NoInputChosen {
            get {
                return ResourceManager.GetString("NoInputChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected to use a single input to iterate the mapping sets, but do not have any inputs sets to be iterators and therefore have not chosen an input to iterate with..
        /// </summary>
        public static string NoInputSet {
            get {
                return ResourceManager.GetString("NoInputSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You enabled the narrative but didn&apos;t specify a narrative file.  Do you want to continue?
        ///
        ///If you choose Yes, the narrative will be disabled..
        /// </summary>
        public static string NoNarrativeFile {
            get {
                return ResourceManager.GetString("NoNarrativeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap none1 {
            get {
                object obj = ResourceManager.GetObject("none1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select cells to search..
        /// </summary>
        public static string NoSelectionToSearch {
            get {
                return ResourceManager.GetString("NoSelectionToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This does not appear to be a valid sequence file..
        /// </summary>
        public static string NotAValidSequence {
            get {
                return ResourceManager.GetString("NotAValidSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap number {
            get {
                object obj = ResourceManager.GetObject("number", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap nutcracker {
            get {
                object obj = ResourceManager.GetObject("nutcracker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap off {
            get {
                object obj = ResourceManager.GetObject("off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string OffText {
            get {
                return ResourceManager.GetString("OffText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap on {
            get {
                object obj = ResourceManager.GetObject("on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program has at least one sequence that has not been saved..
        /// </summary>
        public static string OneOrMoreSequencesNotSaved {
            get {
                return ResourceManager.GetString("OneOrMoreSequencesNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string OnText {
            get {
                return ResourceManager.GetString("OnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap open {
            get {
                object obj = ResourceManager.GetObject("open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free or open source
        ///projects used:.
        /// </summary>
        public static string OpenSource {
            get {
                return ResourceManager.GetString("OpenSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name is already in use.
        ///Do you want to overwrite it?.
        /// </summary>
        public static string OrderNameOverwrite {
            get {
                return ResourceManager.GetString("OrderNameOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File already exists.  Overwrite?.
        /// </summary>
        public static string OverwriteFilePrompt {
            get {
                return ResourceManager.GetString("OverwriteFilePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name is already in use.
        ///Do you want to overwrite it?.
        /// </summary>
        public static string OverwriteNamePrompt {
            get {
                return ResourceManager.GetString("OverwriteNamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap partial_fade {
            get {
                object obj = ResourceManager.GetObject("partial_fade", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap partial_ramp {
            get {
                object obj = ResourceManager.GetObject("partial_ramp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap paste {
            get {
                object obj = ResourceManager.GetObject("paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap paste_bool {
            get {
                object obj = ResourceManager.GetObject("paste_bool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap paste_ins {
            get {
                object obj = ResourceManager.GetObject("paste_ins", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap paste_math {
            get {
                object obj = ResourceManager.GetObject("paste_math", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap paste_trans {
            get {
                object obj = ResourceManager.GetObject("paste_trans", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string PasteText {
            get {
                return ResourceManager.GetString("PasteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pause {
            get {
                object obj = ResourceManager.GetObject("pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Percent {
            get {
                object obj = ResourceManager.GetObject("Percent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap play {
            get {
                object obj = ResourceManager.GetObject("play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap play_from {
            get {
                object obj = ResourceManager.GetObject("play_from", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap play_range {
            get {
                object obj = ResourceManager.GetObject("play_range", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play this sequence starting at the selection startPoint (F6).
        /// </summary>
        public static string PlayFromStartPoint {
            get {
                return ResourceManager.GetString("PlayFromStartPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play the selected range of this sequence (F6).
        /// </summary>
        public static string PlayRange {
            get {
                return ResourceManager.GetString("PlayRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin error.
        /// </summary>
        public static string PluginError {
            get {
                return ResourceManager.GetString("PluginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred when trying to initialize the plugin for setup.
        ///
        ///Error:
        ///.
        /// </summary>
        public static string PluginInitError {
            get {
                return ResourceManager.GetString("PluginInitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during plugin initialization:
        ///
        ///{0}
        ///
        ///The plugin&apos;s setup data may be invalid or inaccurate..
        /// </summary>
        public static string PluginSetupErrorInvalidStatePossible {
            get {
                return ResourceManager.GetString("PluginSetupErrorInvalidStatePossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Name.
        /// </summary>
        public static string ProfileNamePrompt {
            get {
                return ResourceManager.GetString("ProfileNamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///Profile not found.
        ///Will use sequence data instead..
        /// </summary>
        public static string ProfileNotFound {
            get {
                return ResourceManager.GetString("ProfileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap quarter_note {
            get {
                object obj = ResourceManager.GetObject("quarter_note", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ramp {
            get {
                object obj = ResourceManager.GetObject("ramp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap random {
            get {
                object obj = ResourceManager.GetObject("random", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap redo {
            get {
                object obj = ResourceManager.GetObject("redo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string RedoText {
            get {
                return ResourceManager.GetString("RedoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to Redo.
        /// </summary>
        public static string RedoTextEmpty {
            get {
                return ResourceManager.GetString("RedoTextEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will reduce the number of channels and potentially lose sequence data.
        ///Groups will be maintained.
        ///
        ///Accept new channel count?.
        /// </summary>
        public static string ReduceChannelCount {
            get {
                return ResourceManager.GetString("ReduceChannelCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap remove {
            get {
                object obj = ResourceManager.GetObject("remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove profile {0}?
        ///
        ///This will affect any sequences and groups that use this profile..
        /// </summary>
        public static string RemoveProfile {
            get {
                return ResourceManager.GetString("RemoveProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the selected item from this profile?.
        /// </summary>
        public static string RemoveProfileItem {
            get {
                return ResourceManager.GetString("RemoveProfileItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Order.
        /// </summary>
        public static string ReorderNameHeading {
            get {
                return ResourceManager.GetString("ReorderNameHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What name would you like to give to this ordering of the channels?.
        /// </summary>
        public static string ReorderNamePrompt {
            get {
                return ResourceManager.GetString("ReorderNamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace specified values in the .
        /// </summary>
        public static string Replace_selected_values_in_the_ {
            get {
                return ResourceManager.GetString("Replace_selected_values_in_the_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application must be restarted for this change to be effective..
        /// </summary>
        public static string RestartForChange {
            get {
                return ResourceManager.GetString("RestartForChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Router)
        ///An output plugin caused the following exception: 
        ///{0}
        ///
        ///Execution has been stopped.
        ///
        ///{1}.
        /// </summary>
        public static string RouterError {
            get {
                return ResourceManager.GetString("RouterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Router - plugins)
        ///An output plugin caused the following exception: 
        ///{0}.
        /// </summary>
        public static string RouterOutputError {
            get {
                return ResourceManager.GetString("RouterOutputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Router - Startup)
        ///{0}.
        /// </summary>
        public static string RouterStartupError {
            get {
                return ResourceManager.GetString("RouterStartupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the routine.
        /// </summary>
        public static string RoutineNamePrompt {
            get {
                return ResourceManager.GetString("RoutineNamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap save_as {
            get {
                object obj = ResourceManager.GetObject("save_as", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this unnamed sequence.
        /// </summary>
        public static string SaveChanges_Unnamed {
            get {
                return ResourceManager.GetString("SaveChanges_Unnamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap saveSm {
            get {
                object obj = ResourceManager.GetObject("saveSm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sequence is not a scripted sequence.
        ///Only a scripted sequence can be selected for background execution..
        /// </summary>
        public static string ScripedSequenceOnly {
            get {
                return ResourceManager.GetString("ScripedSequenceOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence length has been updated..
        /// </summary>
        public static string SequenceLengthUpdated {
            get {
                return ResourceManager.GetString("SequenceLengthUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before a program can be saved, the contained sequences need to be saved..
        /// </summary>
        public static string SequencesMustBeSavedBeforeSavingProgram {
            get {
                return ResourceManager.GetString("SequencesMustBeSavedBeforeSavingProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap setLevel {
            get {
                object obj = ResourceManager.GetObject("setLevel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set the sequence length.
        ///There is audio associated which would exceed that length..
        /// </summary>
        public static string SetProgramTimeError {
            get {
                return ResourceManager.GetString("SetProgramTimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap shimmer {
            get {
                object obj = ResourceManager.GetObject("shimmer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shimmer (dimming).
        /// </summary>
        public static string ShimmerPrompt {
            get {
                return ResourceManager.GetString("ShimmerPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show actual levels.
        /// </summary>
        public static string ShowActual {
            get {
                return ResourceManager.GetString("ShowActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show % levels.
        /// </summary>
        public static string ShowPercentage {
            get {
                return ResourceManager.GetString("ShowPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap sliders {
            get {
                object obj = ResourceManager.GetObject("sliders", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {3} has had a non-critical error and may be able to continue.
        ///
        ///If you continue, please save any open work and restart {3}.
        ///
        ///This issue was written to {0}, please e-mail this log, your sequence and profile (if applicable) with any support request.
        ///
        ///{1}
        ///
        ///{2}
        ///
        ///Do you wish to continue?.
        /// </summary>
        public static string SoftErrorOccured {
            get {
                return ResourceManager.GetString("SoftErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap sparkle {
            get {
                object obj = ResourceManager.GetObject("sparkle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap stop {
            get {
                object obj = ResourceManager.GetObject("stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete channel &apos;{0}&apos;?
        ///    
        ///This cannot be undone and your undo history will be cleared..
        /// </summary>
        public static string StringFormat_DeleteChannel {
            get {
                return ResourceManager.GetString("StringFormat_DeleteChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete channel order &apos;{0}&apos;?.
        /// </summary>
        public static string StringFormat_DeleteChannelOrder {
            get {
                return ResourceManager.GetString("StringFormat_DeleteChannelOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing level adjusted to {0}.
        ///It was {1} which was above the sequence maximum..
        /// </summary>
        public static string StringFormat_DrawingLevelAbove {
            get {
                return ResourceManager.GetString("StringFormat_DrawingLevelAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing level adjusted to {0}.
        ///It was {1} which was below the sequence minimum..
        /// </summary>
        public static string StringFormat_DrawingLevelBelow {
            get {
                return ResourceManager.GetString("StringFormat_DrawingLevelBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routine &quot;{0}&quot; has been saved.
        /// </summary>
        public static string StringFormat_RoutineSaved {
            get {
                return ResourceManager.GetString("StringFormat_RoutineSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes to {0}?.
        /// </summary>
        public static string StringFormat_SaveChanges {
            get {
                return ResourceManager.GetString("StringFormat_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap subtract {
            get {
                object obj = ResourceManager.GetObject("subtract", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap test_channels {
            get {
                object obj = ResourceManager.GetObject("test_channels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beta Tested By:.
        /// </summary>
        public static string TestedBy {
            get {
                return ResourceManager.GetString("TestedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text file.
        /// </summary>
        public static string TextFile {
            get {
                return ResourceManager.GetString("TextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you everyone!
        ///    .
        /// </summary>
        public static string ThankYou {
            get {
                return ResourceManager.GetString("ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap three_quarter_note {
            get {
                object obj = ResourceManager.GetObject("three_quarter_note", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A timer with an unknown object tried to execute..
        /// </summary>
        public static string TimerUnknownError {
            get {
                return ResourceManager.GetString("TimerUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an engine assembly.
        /// </summary>
        public static string Title_SelectEngine {
            get {
                return ResourceManager.GetString("Title_SelectEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbar Settings Saved..
        /// </summary>
        public static string ToolbarSettingsSaved {
            get {
                return ResourceManager.GetString("ToolbarSettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show actual intensity levels (0-255).
        /// </summary>
        public static string ToolTip_IntensityLevel {
            get {
                return ResourceManager.GetString("ToolTip_IntensityLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show intensity levels as percent (0-100%).
        /// </summary>
        public static string ToolTip_IntensityPercent {
            get {
                return ResourceManager.GetString("ToolTip_IntensityPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translated By:.
        /// </summary>
        public static string TranslatedBy {
            get {
                return ResourceManager.GetString("TranslatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No One Yet!
        ///.
        /// </summary>
        public static string Translators {
            get {
                return ResourceManager.GetString("Translators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the song..
        /// </summary>
        public static string UnableToLoadSong {
            get {
                return ResourceManager.GetString("UnableToLoadSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  -- unassigned -- .
        /// </summary>
        public static string Unassigned {
            get {
                return ResourceManager.GetString("Unassigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap undo {
            get {
                object obj = ResourceManager.GetObject("undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string UndoText {
            get {
                return ResourceManager.GetString("UndoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust Intensity.
        /// </summary>
        public static string UndoText_AdjustIntensity {
            get {
                return ResourceManager.GetString("UndoText_AdjustIntensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arithmetic Paste.
        /// </summary>
        public static string UndoText_ArithmeticPaste {
            get {
                return ResourceManager.GetString("UndoText_ArithmeticPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean Paste.
        /// </summary>
        public static string UndoText_BooleanPaste {
            get {
                return ResourceManager.GetString("UndoText_BooleanPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chase Lines.
        /// </summary>
        public static string UndoText_ChaseLines {
            get {
                return ResourceManager.GetString("UndoText_ChaseLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All Events.
        /// </summary>
        public static string UndoText_ClearAllEvents {
            get {
                return ResourceManager.GetString("UndoText_ClearAllEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Channel.
        /// </summary>
        public static string UndoText_ClearChannel {
            get {
                return ResourceManager.GetString("UndoText_ClearChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Values.
        /// </summary>
        public static string UndoText_ClearValues {
            get {
                return ResourceManager.GetString("UndoText_ClearValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Channel Data.
        /// </summary>
        public static string UndoText_CopyChannelData {
            get {
                return ResourceManager.GetString("UndoText_CopyChannelData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Click.
        /// </summary>
        public static string UndoText_DoubleClick {
            get {
                return ResourceManager.GetString("UndoText_DoubleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event On.
        /// </summary>
        public static string UndoText_EventOn {
            get {
                return ResourceManager.GetString("UndoText_EventOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fade.
        /// </summary>
        public static string UndoText_Fade {
            get {
                return ResourceManager.GetString("UndoText_Fade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill.
        /// </summary>
        public static string UndoText_Fill {
            get {
                return ResourceManager.GetString("UndoText_Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Paste.
        /// </summary>
        public static string UndoText_InsertPaste {
            get {
                return ResourceManager.GetString("UndoText_InsertPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intensity.
        /// </summary>
        public static string UndoText_Intensity {
            get {
                return ResourceManager.GetString("UndoText_Intensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert.
        /// </summary>
        public static string UndoText_Invert {
            get {
                return ResourceManager.GetString("UndoText_Invert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpaquePaste.
        /// </summary>
        public static string UndoText_OpaquePaste {
            get {
                return ResourceManager.GetString("UndoText_OpaquePaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial.
        /// </summary>
        public static string UndoText_Partial {
            get {
                return ResourceManager.GetString("UndoText_Partial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ramp.
        /// </summary>
        public static string UndoText_Ramp {
            get {
                return ResourceManager.GetString("UndoText_Ramp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        public static string UndoText_Random {
            get {
                return ResourceManager.GetString("UndoText_Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Cells.
        /// </summary>
        public static string UndoText_RemoveCells {
            get {
                return ResourceManager.GetString("UndoText_RemoveCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shimmer.
        /// </summary>
        public static string UndoText_Shimmer {
            get {
                return ResourceManager.GetString("UndoText_Shimmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sparkle.
        /// </summary>
        public static string UndoText_Sparkle {
            get {
                return ResourceManager.GetString("UndoText_Sparkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparent Paste.
        /// </summary>
        public static string UndoText_TransparentPaste {
            get {
                return ResourceManager.GetString("UndoText_TransparentPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to Undo.
        /// </summary>
        public static string UndoTextEmpty {
            get {
                return ResourceManager.GetString("UndoTextEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unnamed Sequence.
        /// </summary>
        public static string UnnamedSequence {
            get {
                return ResourceManager.GetString("UnnamedSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unselect All.
        /// </summary>
        public static string UnselectAll {
            get {
                return ResourceManager.GetString("UnselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use application&apos;s default device.
        /// </summary>
        public static string UseApplicationDefaultAudio {
            get {
                return ResourceManager.GetString("UseApplicationDefaultAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sequence is attached to a profile.
        ///Edit the profile to make changes to the channel information..
        /// </summary>
        public static string UseProfileToEditChannels {
            get {
                return ResourceManager.GetString("UseProfileToEditChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid number..
        /// </summary>
        public static string ValidNumber {
            get {
                return ResourceManager.GetString("ValidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will reset all values of the selected channel.
        ///
        ///Continue?.
        /// </summary>
        public static string VerifyChannelValueReset {
            get {
                return ResourceManager.GetString("VerifyChannelValueReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add-in error:
        ///
        ///.
        /// </summary>
        public static string VixenPlusForm_AddInError {
            get {
                return ResourceManager.GetString("VixenPlusForm_AddInError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay cannot be less than 1 second.
        ///Resetting to 1 second.
        /// </summary>
        public static string VixenPlusForm_DelayPeriodMin {
            get {
                return ResourceManager.GetString("VixenPlusForm_DelayPeriodMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event period length cannot be less than {0} milliseconds and
        ///will be set to {0} milliseconds..
        /// </summary>
        public static string VixenPlusForm_EventPeriodMin {
            get {
                return ResourceManager.GetString("VixenPlusForm_EventPeriodMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist.
        ///Item has been removed from the history..
        /// </summary>
        public static string VixenPlusForm_HistoryRemovalMsg {
            get {
                return ResourceManager.GetString("VixenPlusForm_HistoryRemovalMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can&apos;t seem to determine which type of file this is, most likely due to a missing profile or corrupt embedded data..
        /// </summary>
        public static string VixenPlusForm_NoKnowEditor {
            get {
                return ResourceManager.GetString("VixenPlusForm_NoKnowEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no sequence open, nor is there a default profile set.
        ///You have no channels to layout..
        /// </summary>
        public static string VixenPlusForm_NoOpenSequence {
            get {
                return ResourceManager.GetString("VixenPlusForm_NoOpenSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is nothing scheduled to execute at this time..
        /// </summary>
        public static string VixenPlusForm_NothingToDoMsg {
            get {
                return ResourceManager.GetString("VixenPlusForm_NothingToDoMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No wizard available.
        ///
        ///A blank sequence will be created for you..
        /// </summary>
        public static string VixenPlusForm_NoWizardMsg {
            get {
                return ResourceManager.GetString("VixenPlusForm_NoWizardMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string VixenPlusForm_Save {
            get {
                return ResourceManager.GetString("VixenPlusForm_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule is currently disabled..
        /// </summary>
        public static string VixenPlusForm_ScheduleDisabledMsg {
            get {
                return ResourceManager.GetString("VixenPlusForm_ScheduleDisabledMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence saved.
        /// </summary>
        public static string VixenPlusForm_SequenceSaved {
            get {
                return ResourceManager.GetString("VixenPlusForm_SequenceSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timers were not executed.
        ///
        ///The scheduled items may be longer than their remaining time or there may have been an error..
        /// </summary>
        public static string VixenPlusForm_TimersNotStarted_TooLong_OrError {
            get {
                return ResourceManager.GetString("VixenPlusForm_TimersNotStarted_TooLong_OrError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger error:
        ///
        ///.
        /// </summary>
        public static string VixenPlusForm_TriggeError {
            get {
                return ResourceManager.GetString("VixenPlusForm_TriggeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger plug in could not be found or started..
        /// </summary>
        public static string VixenPlusForm_TriggerNotFoundOrStarted {
            get {
                return ResourceManager.GetString("VixenPlusForm_TriggerNotFoundOrStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap VixenPlusSplash {
            get {
                object obj = ResourceManager.GetObject("VixenPlusSplash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap wave {
            get {
                object obj = ResourceManager.GetObject("wave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap whole_note {
            get {
                object obj = ResourceManager.GetObject("whole_note", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Written By:.
        /// </summary>
        public static string WrittenBy {
            get {
                return ResourceManager.GetString("WrittenBy", resourceCulture);
            }
        }
    }
}
