//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is missing or does not contain a valid engine.
        /// </summary>
        internal static string EngineMissingOrInvalid {
            get {
                return ResourceManager.GetString("EngineMissingOrInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when shutting down the plugin:
        ///.
        /// </summary>
        internal static string engineShutDownError {
            get {
                return ResourceManager.GetString("engineShutDownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///Execution has been stopped..
        /// </summary>
        internal static string EngineStoppedError {
            get {
                return ResourceManager.GetString("EngineStoppedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin error.
        /// </summary>
        internal static string EngineStoppedHeading {
            get {
                return ResourceManager.GetString("EngineStoppedHeading", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap VixenPlus {
            get {
                object obj = ResourceManager.GetObject("VixenPlus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add-in error:
        ///
        ///.
        /// </summary>
        internal static string VixenPlusForm_AddInError {
            get {
                return ResourceManager.GetString("VixenPlusForm_AddInError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay cannot be less than 1 second.
        ///Resetting to 1 second.
        /// </summary>
        internal static string VixenPlusForm_DelayPeriodMin {
            get {
                return ResourceManager.GetString("VixenPlusForm_DelayPeriodMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event period length cannot be less than 25 milliseconds.
        ///The length has been reset to 25 milliseconds..
        /// </summary>
        internal static string VixenPlusForm_EventPeriodMin {
            get {
                return ResourceManager.GetString("VixenPlusForm_EventPeriodMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist.
        ///Item has been removed from the history..
        /// </summary>
        internal static string VixenPlusForm_HistoryRemovalMsg {
            get {
                return ResourceManager.GetString("VixenPlusForm_HistoryRemovalMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no known editor for that file type..
        /// </summary>
        internal static string VixenPlusForm_NoKnowEditor {
            get {
                return ResourceManager.GetString("VixenPlusForm_NoKnowEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no sequence open, nor is there a default profile set.
        ///You have no channels to layout..
        /// </summary>
        internal static string VixenPlusForm_NoOpenSequence {
            get {
                return ResourceManager.GetString("VixenPlusForm_NoOpenSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is nothing scheduled to execute at this time..
        /// </summary>
        internal static string VixenPlusForm_NothingToDoMsg {
            get {
                return ResourceManager.GetString("VixenPlusForm_NothingToDoMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No wizard available.
        ///
        ///A blank sequence will be created for you..
        /// </summary>
        internal static string VixenPlusForm_NoWizardMsg {
            get {
                return ResourceManager.GetString("VixenPlusForm_NoWizardMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string VixenPlusForm_Save {
            get {
                return ResourceManager.GetString("VixenPlusForm_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule is currently disabled..
        /// </summary>
        internal static string VixenPlusForm_ScheduleDisabledMsg {
            get {
                return ResourceManager.GetString("VixenPlusForm_ScheduleDisabledMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence saved.
        /// </summary>
        internal static string VixenPlusForm_SequenceSaved {
            get {
                return ResourceManager.GetString("VixenPlusForm_SequenceSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timers were not executed.
        ///
        ///The scheduled items may be longer than their remaining time or there may have been an error..
        /// </summary>
        internal static string VixenPlusForm_TimersNotStarted_TooLong_OrError {
            get {
                return ResourceManager.GetString("VixenPlusForm_TimersNotStarted_TooLong_OrError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger error:
        ///
        ///.
        /// </summary>
        internal static string VixenPlusForm_TriggeError {
            get {
                return ResourceManager.GetString("VixenPlusForm_TriggeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger plug in could not be found or started..
        /// </summary>
        internal static string VixenPlusForm_TriggerNotFoundOrStarted {
            get {
                return ResourceManager.GetString("VixenPlusForm_TriggerNotFoundOrStarted", resourceCulture);
            }
        }
    }
}
