namespace VixenPlus{
    using System;
    using System.Windows.Forms;
    using System.Drawing;
    using System.ComponentModel;
    using System.Collections;

    internal sealed partial class ProgramManagerDialog{
        private IContainer components;

        #region Windows Form Designer generated code
        private AddEditRemove addEditRemove;
private Button buttonCancel;
private Button buttonOK;
private Button buttonRadioAction;
private GroupBox groupBox1;
private GroupBox groupBox2;
private GroupBox groupBox3;
private GroupBox groupBoxProgramPlugin;
private Label label1;
private Label labelProgramName;
private ListBox listBoxPrograms;
private ListBox listBoxProgramSequences;
private ListBox listBoxSequences;
private NumericUpDown numericUpDownCrossFade;
private OpenFileDialog openFileDialog;
private PictureBox pictureBoxRun;
private PictureBox pictureBoxRunProgram;
private PictureBox pictureBoxStop;
private RadioButton radioButtonProfile;
private RadioButton radioButtonProgramPlugin;
private RadioButton radioButtonSequencePlugin;
private System.Windows.Forms.Timer timer;

        private void InitializeComponent()
        {
            this.components = new Container();
            this.listBoxPrograms = new ListBox();
            this.listBoxProgramSequences = new ListBox();
            this.groupBox1 = new GroupBox();
            this.addEditRemove = new AddEditRemove(this.components);
            this.groupBox2 = new GroupBox();
            this.buttonOK = new Button();
            this.buttonCancel = new Button();
            this.listBoxSequences = new ListBox();
            this.groupBox3 = new GroupBox();
            this.groupBoxProgramPlugin = new GroupBox();
            this.label1 = new Label();
            this.numericUpDownCrossFade = new NumericUpDown();
            this.radioButtonSequencePlugin = new RadioButton();
            this.pictureBoxRunProgram = new PictureBox();
            this.buttonRadioAction = new Button();
            this.radioButtonProfile = new RadioButton();
            this.radioButtonProgramPlugin = new RadioButton();
            this.labelProgramName = new Label();
            this.openFileDialog = new OpenFileDialog();
            this.pictureBoxRun = new PictureBox();
            this.pictureBoxStop = new PictureBox();
            this.timer = new System.Windows.Forms.Timer(this.components);
            this.groupBox1.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.groupBox3.SuspendLayout();
            this.groupBoxProgramPlugin.SuspendLayout();
            this.numericUpDownCrossFade.BeginInit();
            ((ISupportInitialize) this.pictureBoxRunProgram).BeginInit();
            ((ISupportInitialize) this.pictureBoxRun).BeginInit();
            ((ISupportInitialize) this.pictureBoxStop).BeginInit();
            base.SuspendLayout();
            this.listBoxPrograms.AllowDrop = true;
            this.listBoxPrograms.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Top;
            this.listBoxPrograms.BackColor = SystemColors.Window;
            this.listBoxPrograms.DrawMode = DrawMode.OwnerDrawFixed;
            this.listBoxPrograms.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.listBoxPrograms.ItemHeight = 0x4b;
            this.listBoxPrograms.Location = new Point(6, 0x2b);
            this.listBoxPrograms.Name = "listBoxPrograms";
            this.listBoxPrograms.Size = new Size(0xdb, 0x130);
            this.listBoxPrograms.TabIndex = 0;
            this.listBoxPrograms.DragDrop += new DragEventHandler(this.listBoxPrograms_DragDrop);
            this.listBoxPrograms.DrawItem += new DrawItemEventHandler(this.listBoxPrograms_DrawItem);
            this.listBoxPrograms.MouseMove += new MouseEventHandler(this.listBoxPrograms_MouseMove);
            this.listBoxPrograms.MouseDown += new MouseEventHandler(this.listBoxPrograms_MouseDown);
            this.listBoxPrograms.KeyDown += new KeyEventHandler(this.listBoxPrograms_KeyDown);
            this.listBoxPrograms.DragOver += new DragEventHandler(this.listBoxPrograms_DragOver);
            this.listBoxProgramSequences.AllowDrop = true;
            this.listBoxProgramSequences.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Bottom | AnchorStyles.Top;
            this.listBoxProgramSequences.DrawMode = DrawMode.OwnerDrawFixed;
            this.listBoxProgramSequences.FormattingEnabled = true;
            this.listBoxProgramSequences.ItemHeight = 0x4b;
            this.listBoxProgramSequences.Location = new Point(6, 0x13);
            this.listBoxProgramSequences.Name = "listBoxProgramSequences";
            this.listBoxProgramSequences.Size = new Size(0xdf, 0x211);
            this.listBoxProgramSequences.TabIndex = 0;
            this.listBoxProgramSequences.DragEnter += new DragEventHandler(this.listBoxProgramSongs_DragEnter);
            this.listBoxProgramSequences.DragDrop += new DragEventHandler(this.listBoxProgramSongs_DragDrop);
            this.listBoxProgramSequences.DrawItem += new DrawItemEventHandler(this.listBoxProgramSongs_DrawItem);
            this.listBoxProgramSequences.MouseMove += new MouseEventHandler(this.listBoxProgramSongs_MouseMove);
            this.listBoxProgramSequences.KeyDown += new KeyEventHandler(this.listBoxProgramSongs_KeyDown);
            this.groupBox1.Anchor = AnchorStyles.Left | AnchorStyles.Bottom | AnchorStyles.Top;
            this.groupBox1.Controls.Add(this.addEditRemove);
            this.groupBox1.Controls.Add(this.listBoxPrograms);
            this.groupBox1.Location = new Point(0xdb, 12);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(0xe7, 0x16b);
            this.groupBox1.TabIndex = 1;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Programs";
            this.addEditRemove.EditVisible = false;
            this.addEditRemove.Location = new Point(0xad, 17);
            this.addEditRemove.Name = "addEditRemove";
            this.addEditRemove.RemoveEnabled = false;
            this.addEditRemove.Size = new Size(0x34, 20);
            this.addEditRemove.TabIndex = 8;
            this.addEditRemove.AddClick += new EventHandler(this.addEditRemove_AddClick);
            this.addEditRemove.RemoveClick += new EventHandler(this.addEditRemove_RemoveClick);
            this.groupBox2.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Bottom | AnchorStyles.Top;
            this.groupBox2.Controls.Add(this.listBoxProgramSequences);
            this.groupBox2.Location = new Point(0x1d0, 12);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new Size(0xeb, 0x234);
            this.groupBox2.TabIndex = 2;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "Program event sequences";
            this.buttonOK.Anchor = AnchorStyles.Right | AnchorStyles.Bottom;
            this.buttonOK.DialogResult = System.Windows.Forms.DialogResult.OK;
            this.buttonOK.Location = new Point(0x21f, 0x246);
            this.buttonOK.Name = "buttonOK";
            this.buttonOK.Size = new Size(0x4b, 23);
            this.buttonOK.TabIndex = 3;
            this.buttonOK.Text = "OK";
            this.buttonOK.UseVisualStyleBackColor = true;
            this.buttonOK.Click += new EventHandler(this.buttonOK_Click);
            this.buttonCancel.Anchor = AnchorStyles.Right | AnchorStyles.Bottom;
            this.buttonCancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.buttonCancel.Location = new Point(0x270, 0x246);
            this.buttonCancel.Name = "buttonCancel";
            this.buttonCancel.Size = new Size(0x4b, 23);
            this.buttonCancel.TabIndex = 4;
            this.buttonCancel.Text = "Cancel";
            this.buttonCancel.UseVisualStyleBackColor = true;
            this.listBoxSequences.AllowDrop = true;
            this.listBoxSequences.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Bottom | AnchorStyles.Top;
            this.listBoxSequences.FormattingEnabled = true;
            this.listBoxSequences.HorizontalScrollbar = true;
            this.listBoxSequences.Location = new Point(12, 0x13);
            this.listBoxSequences.Name = "listBoxSequences";
            this.listBoxSequences.Size = new Size(0xa8, 0x20c);
            this.listBoxSequences.TabIndex = 0;
            this.listBoxSequences.DragEnter += new DragEventHandler(this.listBoxSongs_DragEnter);
            this.listBoxSequences.DragDrop += new DragEventHandler(this.listBoxSongs_DragDrop);
            this.listBoxSequences.MouseMove += new MouseEventHandler(this.listBoxSongs_MouseMove);
            this.groupBox3.Anchor = AnchorStyles.Left | AnchorStyles.Bottom | AnchorStyles.Top;
            this.groupBox3.Controls.Add(this.listBoxSequences);
            this.groupBox3.Location = new Point(12, 12);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new Size(0xc2, 0x234);
            this.groupBox3.TabIndex = 0;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "Available sequences";
            this.groupBoxProgramPlugin.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.groupBoxProgramPlugin.Controls.Add(this.label1);
            this.groupBoxProgramPlugin.Controls.Add(this.numericUpDownCrossFade);
            this.groupBoxProgramPlugin.Controls.Add(this.radioButtonSequencePlugin);
            this.groupBoxProgramPlugin.Controls.Add(this.pictureBoxRunProgram);
            this.groupBoxProgramPlugin.Controls.Add(this.buttonRadioAction);
            this.groupBoxProgramPlugin.Controls.Add(this.radioButtonProfile);
            this.groupBoxProgramPlugin.Controls.Add(this.radioButtonProgramPlugin);
            this.groupBoxProgramPlugin.Controls.Add(this.labelProgramName);
            this.groupBoxProgramPlugin.Enabled = false;
            this.groupBoxProgramPlugin.Location = new Point(0xdb, 0x17d);
            this.groupBoxProgramPlugin.Name = "groupBoxProgramPlugin";
            this.groupBoxProgramPlugin.Size = new Size(0xe7, 0xc3);
            this.groupBoxProgramPlugin.TabIndex = 5;
            this.groupBoxProgramPlugin.TabStop = false;
            this.groupBoxProgramPlugin.EnabledChanged += new EventHandler(this.groupBoxProgramPlugin_EnabledChanged);
            this.label1.Location = new Point(64, 0x94);
            this.label1.Name = "label1";
            this.label1.Size = new Size(0x8f, 0x1f);
            this.label1.TabIndex = 7;
            this.label1.Text = "second(s) of cross-fade between sequences";
            this.numericUpDownCrossFade.Location = new Point(10, 0x9a);
            this.numericUpDownCrossFade.Name = "numericUpDownCrossFade";
            this.numericUpDownCrossFade.Size = new Size(0x30, 20);
            this.numericUpDownCrossFade.TabIndex = 6;
            this.numericUpDownCrossFade.ValueChanged += new EventHandler(this.numericUpDownCrossFade_ValueChanged);
            this.numericUpDownCrossFade.Leave += new EventHandler(this.numericUpDownCrossFade_Leave);
            this.radioButtonSequencePlugin.AutoSize = true;
            this.radioButtonSequencePlugin.Location = new Point(10, 0x55);
            this.radioButtonSequencePlugin.Name = "radioButtonSequencePlugin";
            this.radioButtonSequencePlugin.Size = new Size(0xbc, 17);
            this.radioButtonSequencePlugin.TabIndex = 3;
            this.radioButtonSequencePlugin.TabStop = true;
            this.radioButtonSequencePlugin.Text = "Use each sequence's plugin setup";
            this.radioButtonSequencePlugin.UseVisualStyleBackColor = true;
            this.radioButtonSequencePlugin.CheckedChanged += new EventHandler(this.radioButtonProgramPlugin_CheckedChanged);
            this.pictureBoxRunProgram.Location = new Point(0xc9, 0x10);
            this.pictureBoxRunProgram.Name = "pictureBoxRunProgram";
            this.pictureBoxRunProgram.Size = new Size(0x10, 0x10);
            this.pictureBoxRunProgram.TabIndex = 4;
            this.pictureBoxRunProgram.TabStop = false;
            this.pictureBoxRunProgram.Visible = false;
            this.pictureBoxRunProgram.Click += new EventHandler(this.pictureBoxRunProgram_Click);
            this.buttonRadioAction.Location = new Point(10, 0x70);
            this.buttonRadioAction.Name = "buttonRadioAction";
            this.buttonRadioAction.Size = new Size(0x58, 23);
            this.buttonRadioAction.TabIndex = 4;
            this.buttonRadioAction.UseVisualStyleBackColor = true;
            this.buttonRadioAction.Click += new EventHandler(this.buttonRadioAction_Click);
            this.radioButtonProfile.AutoSize = true;
            this.radioButtonProfile.Location = new Point(10, 0x3d);
            this.radioButtonProfile.Name = "radioButtonProfile";
            this.radioButtonProfile.Size = new Size(0x54, 17);
            this.radioButtonProfile.TabIndex = 2;
            this.radioButtonProfile.Text = "Use a profile";
            this.radioButtonProfile.UseVisualStyleBackColor = true;
            this.radioButtonProfile.CheckedChanged += new EventHandler(this.radioButtonProgramPlugin_CheckedChanged);
            this.radioButtonProgramPlugin.AutoSize = true;
            this.radioButtonProgramPlugin.Location = new Point(10, 0x25);
            this.radioButtonProgramPlugin.Name = "radioButtonProgramPlugin";
            this.radioButtonProgramPlugin.Size = new Size(0x98, 17);
            this.radioButtonProgramPlugin.TabIndex = 1;
            this.radioButtonProgramPlugin.Text = "Use program's plugin setup";
            this.radioButtonProgramPlugin.UseVisualStyleBackColor = true;
            this.radioButtonProgramPlugin.CheckedChanged += new EventHandler(this.radioButtonProgramPlugin_CheckedChanged);
            this.labelProgramName.AutoSize = true;
            this.labelProgramName.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.labelProgramName.Location = new Point(7, 17);
            this.labelProgramName.Name = "labelProgramName";
            this.labelProgramName.Size = new Size(0x7c, 13);
            this.labelProgramName.TabIndex = 0;
            this.labelProgramName.Text = "No program selected";
            this.pictureBoxRun.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.pictureBoxRun.Location = new Point(12, 0x249);
            this.pictureBoxRun.Name = "pictureBoxRun";
            this.pictureBoxRun.Size = new Size(0x10, 0x10);
            this.pictureBoxRun.TabIndex = 6;
            this.pictureBoxRun.TabStop = false;
            this.pictureBoxRun.Visible = false;
            this.pictureBoxStop.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.pictureBoxStop.Location = new Point(0x26, 0x249);
            this.pictureBoxStop.Name = "pictureBoxStop";
            this.pictureBoxStop.Size = new Size(0x10, 0x10);
            this.pictureBoxStop.TabIndex = 7;
            this.pictureBoxStop.TabStop = false;
            this.pictureBoxStop.Visible = false;
            this.timer.Tick += new EventHandler(this.timer_Tick);
            this.AllowDrop = true;
            base.AutoScaleDimensions = new SizeF(6f, 13f);
            base.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            base.ClientSize = new Size(0x2c5, 0x269);
            base.Controls.Add(this.pictureBoxStop);
            base.Controls.Add(this.pictureBoxRun);
            base.Controls.Add(this.groupBoxProgramPlugin);
            base.Controls.Add(this.groupBox3);
            base.Controls.Add(this.buttonCancel);
            base.Controls.Add(this.buttonOK);
            base.Controls.Add(this.groupBox2);
            base.Controls.Add(this.groupBox1);
            base.Name = "ProgramManagerDialog";
            base.StartPosition = FormStartPosition.CenterScreen;
            this.Text = "Program Management";
            base.DragDrop += new DragEventHandler(this.ProgramManagerDialog_DragDrop);
            base.FormClosing += new FormClosingEventHandler(this.ProgramManagerDialog_FormClosing);
            base.DragEnter += new DragEventHandler(this.ProgramManagerDialog_DragEnter);
            this.groupBox1.ResumeLayout(false);
            this.groupBox2.ResumeLayout(false);
            this.groupBox3.ResumeLayout(false);
            this.groupBoxProgramPlugin.ResumeLayout(false);
            this.groupBoxProgramPlugin.PerformLayout();
            this.numericUpDownCrossFade.EndInit();
            ((ISupportInitialize) this.pictureBoxRunProgram).EndInit();
            ((ISupportInitialize) this.pictureBoxRun).EndInit();
            ((ISupportInitialize) this.pictureBoxStop).EndInit();
            base.ResumeLayout(false);
        }
        #endregion

        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            if (this._programBrush != null)
            {
                this._programBrush.Dispose();
            }
            if (this._programBoldFont != null)
            {
                this._programBoldFont.Dispose();
            }
            if (this._programSmallFont != null)
            {
                this._programSmallFont.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}
