using System;
using System.Windows.Forms;
using System.Drawing;
using System.ComponentModel;
using System.Collections;

namespace LedTriks
{
	public partial class LedTriks
	{
		private IContainer components;

		#region Windows Form Designer generated code
		private ToolStripMenuItem attachedPluginsToolStripMenuItem;
		private ToolStripMenuItem autoresetAutoTextDefaultsToolStripMenuItem;
		private ToolStripMenuItem boardLayoutToolStripMenuItem;
		private Button buttonClear;
		private Button buttonClone;
		private Button buttonCreateAutoText;
		private Button buttonFont;
		private Button buttonNext;
		private Button buttonOrganize;
		private Button buttonPrevious;
		private Button buttonRemove;
		private Button buttonRemoveAll;
		private Button buttonSaveAndCreateNew;
		private Button buttonSaveFrame;
		private ToolStripMenuItem cellSizeToolStripMenuItem;
		private CheckBox checkBoxLoop;
		private ToolStripMenuItem confirmOnFrameRemoveToolStripMenuItem;
		private ToolStripMenuItem copyThisFrameToolStripMenuItem;
		private ToolStripMenuItem defaultFrameLengthToolStripMenuItem;
		private ToolStripMenuItem executeToolStripMenuItem;
		private FontDialog fontDialog;
		private ToolStripMenuItem ghostThePreviousFrameToolStripMenuItem;
		private GroupBox groupBoxAutoText;
		private GroupBox groupBoxCurrentFrame;
		private GroupBox groupBoxDisplay;
		private GroupBox groupBoxPreviewControl;
		private ToolStripMenuItem ignoreFontDescentToolStripMenuItem;
		private Label label1;
		private Label label2;
		private Label label3;
		private Label labelCurrentFrame;
		private Label labelFontName;
		private Label labelLength;
		private Label labelPosition;
		private ToolStripMenuItem ledTriksToolStripMenuItem;
		private LinkLabel linkLabelMoreOptions;
		private MouseButtons m_mouseDown;
		private MenuStrip menuStrip;
		private Panel panel;
		private Panel panel1;
		private ToolStripMenuItem pasteToolStripMenuItem;
		private PictureBox pictureBoxPlay;
		private PictureBox pictureBoxPlayFromBeginning;
		private PictureBox pictureBoxPreview;
		private PictureBox pictureBoxShiftDown;
		private PictureBox pictureBoxShiftLeft;
		private PictureBox pictureBoxShiftRight;
		private PictureBox pictureBoxShiftUp;
		private PictureBox pictureBoxStop;
		private ToolStripMenuItem playControlButtonsToolStripMenuItem;
		private ToolStripMenuItem previewToolStripMenuItem;
		private ToolStripMenuItem saveAsToolStripMenuItem;
		private SaveFileDialog saveFileDialog;
		private ToolStripMenuItem saveToolStripMenuItem;
		private ToolStripMenuItem sequenceToolStripMenuItem;
		private TextBox textBoxAutoText;
		private TextBox textBoxFrameLength;
		private ToolStripSeparator toolStripMenuItem1;
		private ToolStripMenuItem toolStripMenuItem10;
		private ToolStripMenuItem toolStripMenuItem11;
		private ToolStripMenuItem toolStripMenuItem12;
		private ToolStripMenuItem toolStripMenuItem13;
		private ToolStripSeparator toolStripMenuItem5;
		private ToolStripSeparator toolStripMenuItem6;
		private ToolStripSeparator toolStripMenuItem7;
		private ToolStripTextBox toolStripTextBoxFrameLength;
		private ToolTip toolTip;
		private TrackBar trackBarFrame;

	//ComponentResourceManager manager = new ComponentResourceManager(typeof(LedTriks));
	//this.pictureBoxShiftUp.Image = (Image)manager.GetObject("pictureBoxShiftUp.Image");
	//this.pictureBoxShiftDown.Image = (Image)manager.GetObject("pictureBoxShiftDown.Image");
	//this.pictureBoxShiftLeft.Image = (Image)manager.GetObject("pictureBoxShiftLeft.Image");
	//this.pictureBoxShiftRight.Image = (Image)manager.GetObject("pictureBoxShiftRight.Image");
	//this.pictureBoxStop.Image = (Image)manager.GetObject("pictureBoxStop.Image");
	//this.pictureBoxPlay.Image = (Image)manager.GetObject("pictureBoxPlay.Image");
	//this.pictureBoxPlayFromBeginning.Image = (Image)manager.GetObject("pictureBoxPlayFromBeginning.Image");

		private void InitializeComponent()
		{
			this.components = new Container();
			this.menuStrip = new MenuStrip();
			this.sequenceToolStripMenuItem = new ToolStripMenuItem();
			this.saveToolStripMenuItem = new ToolStripMenuItem();
			this.saveAsToolStripMenuItem = new ToolStripMenuItem();
			this.toolStripMenuItem6 = new ToolStripSeparator();
			this.ledTriksToolStripMenuItem = new ToolStripMenuItem();
			this.boardLayoutToolStripMenuItem = new ToolStripMenuItem();
			this.cellSizeToolStripMenuItem = new ToolStripMenuItem();
			this.toolStripMenuItem10 = new ToolStripMenuItem();
			this.toolStripMenuItem11 = new ToolStripMenuItem();
			this.toolStripMenuItem12 = new ToolStripMenuItem();
			this.toolStripMenuItem13 = new ToolStripMenuItem();
			this.defaultFrameLengthToolStripMenuItem = new ToolStripMenuItem();
			this.toolStripTextBoxFrameLength = new ToolStripTextBox();
			this.toolStripMenuItem1 = new ToolStripSeparator();
			this.ignoreFontDescentToolStripMenuItem = new ToolStripMenuItem();
			this.confirmOnFrameRemoveToolStripMenuItem = new ToolStripMenuItem();
			this.ghostThePreviousFrameToolStripMenuItem = new ToolStripMenuItem();
			this.autoresetAutoTextDefaultsToolStripMenuItem = new ToolStripMenuItem();
			this.toolStripMenuItem5 = new ToolStripSeparator();
			this.copyThisFrameToolStripMenuItem = new ToolStripMenuItem();
			this.pasteToolStripMenuItem = new ToolStripMenuItem();
			this.toolStripMenuItem7 = new ToolStripSeparator();
			this.attachedPluginsToolStripMenuItem = new ToolStripMenuItem();
			this.playControlButtonsToolStripMenuItem = new ToolStripMenuItem();
			this.previewToolStripMenuItem = new ToolStripMenuItem();
			this.executeToolStripMenuItem = new ToolStripMenuItem();
			this.panel = new Panel();
			this.checkBoxLoop = new CheckBox();
			this.groupBoxCurrentFrame = new GroupBox();
			this.buttonClone = new Button();
			this.label2 = new Label();
			this.textBoxFrameLength = new TextBox();
			this.label3 = new Label();
			this.buttonSaveFrame = new Button();
			this.buttonSaveAndCreateNew = new Button();
			this.pictureBoxShiftUp = new PictureBox();
			this.buttonClear = new Button();
			this.pictureBoxShiftDown = new PictureBox();
			this.pictureBoxShiftLeft = new PictureBox();
			this.pictureBoxShiftRight = new PictureBox();
			this.groupBoxAutoText = new GroupBox();
			this.linkLabelMoreOptions = new LinkLabel();
			this.buttonCreateAutoText = new Button();
			this.textBoxAutoText = new TextBox();
			this.labelFontName = new Label();
			this.buttonFont = new Button();
			this.buttonOrganize = new Button();
			this.labelLength = new Label();
			this.label1 = new Label();
			this.groupBoxDisplay = new GroupBox();
			this.panel1 = new Panel();
			this.pictureBoxPreview = new PictureBox();
			this.buttonNext = new Button();
			this.labelPosition = new Label();
			this.buttonPrevious = new Button();
			this.labelCurrentFrame = new Label();
			this.buttonRemoveAll = new Button();
			this.buttonRemove = new Button();
			this.trackBarFrame = new TrackBar();
			this.groupBoxPreviewControl = new GroupBox();
			this.pictureBoxStop = new PictureBox();
			this.pictureBoxPlayFromBeginning = new PictureBox();
			this.pictureBoxPlay = new PictureBox();
			this.toolTip = new ToolTip(this.components);
			this.fontDialog = new FontDialog();
			this.saveFileDialog = new SaveFileDialog();
			this.menuStrip.SuspendLayout();
			this.panel.SuspendLayout();
			this.groupBoxCurrentFrame.SuspendLayout();
			((ISupportInitialize) this.pictureBoxShiftUp).BeginInit();
			((ISupportInitialize) this.pictureBoxShiftDown).BeginInit();
			((ISupportInitialize) this.pictureBoxShiftLeft).BeginInit();
			((ISupportInitialize) this.pictureBoxShiftRight).BeginInit();
			this.groupBoxAutoText.SuspendLayout();
			this.groupBoxDisplay.SuspendLayout();
			this.panel1.SuspendLayout();
			((ISupportInitialize) this.pictureBoxPreview).BeginInit();
			this.trackBarFrame.BeginInit();
			this.groupBoxPreviewControl.SuspendLayout();
			((ISupportInitialize) this.pictureBoxStop).BeginInit();
			((ISupportInitialize) this.pictureBoxPlayFromBeginning).BeginInit();
			((ISupportInitialize) this.pictureBoxPlay).BeginInit();
			base.SuspendLayout();
			this.menuStrip.Items.AddRange(new ToolStripItem[] { this.sequenceToolStripMenuItem, this.ledTriksToolStripMenuItem });
			this.menuStrip.Location = new Point(0, 0);
			this.menuStrip.Name = "menuStrip";
			this.menuStrip.Size = new Size(0x318, 24);
			this.menuStrip.TabIndex = 0;
			this.menuStrip.Text = "menuStrip1";
			this.menuStrip.Visible = false;
			this.sequenceToolStripMenuItem.DropDownItems.AddRange(new ToolStripItem[] { this.saveToolStripMenuItem, this.saveAsToolStripMenuItem, this.toolStripMenuItem6 });
			this.sequenceToolStripMenuItem.MergeAction = MergeAction.MatchOnly;
			this.sequenceToolStripMenuItem.Name = "sequenceToolStripMenuItem";
			this.sequenceToolStripMenuItem.Size = new Size(70, 20);
			this.sequenceToolStripMenuItem.Text = "Sequence";
			this.saveToolStripMenuItem.MergeIndex = 3;
			this.saveToolStripMenuItem.Name = "saveToolStripMenuItem";
			this.saveToolStripMenuItem.Size = new Size(0x70, 22);
			this.saveToolStripMenuItem.Text = "Save";
			this.saveToolStripMenuItem.Visible = false;
			this.saveToolStripMenuItem.Click += new EventHandler(this.saveToolStripMenuItem_Click);
			this.saveAsToolStripMenuItem.MergeIndex = 4;
			this.saveAsToolStripMenuItem.Name = "saveAsToolStripMenuItem";
			this.saveAsToolStripMenuItem.Size = new Size(0x70, 22);
			this.saveAsToolStripMenuItem.Text = "Save as";
			this.saveAsToolStripMenuItem.Visible = false;
			this.saveAsToolStripMenuItem.Click += new EventHandler(this.saveAsToolStripMenuItem_Click);
			this.toolStripMenuItem6.MergeIndex = 5;
			this.toolStripMenuItem6.Name = "toolStripMenuItem6";
			this.toolStripMenuItem6.Size = new Size(0x6d, 6);
			this.toolStripMenuItem6.Visible = false;
			this.ledTriksToolStripMenuItem.DropDownItems.AddRange(new ToolStripItem[] { this.boardLayoutToolStripMenuItem, this.cellSizeToolStripMenuItem, this.defaultFrameLengthToolStripMenuItem, this.toolStripMenuItem1, this.ignoreFontDescentToolStripMenuItem, this.confirmOnFrameRemoveToolStripMenuItem, this.ghostThePreviousFrameToolStripMenuItem, this.autoresetAutoTextDefaultsToolStripMenuItem, this.toolStripMenuItem5, this.copyThisFrameToolStripMenuItem, this.pasteToolStripMenuItem, this.toolStripMenuItem7, this.attachedPluginsToolStripMenuItem, this.playControlButtonsToolStripMenuItem });
			this.ledTriksToolStripMenuItem.MergeAction = MergeAction.Insert;
			this.ledTriksToolStripMenuItem.MergeIndex = 5;
			this.ledTriksToolStripMenuItem.Name = "ledTriksToolStripMenuItem";
			this.ledTriksToolStripMenuItem.Size = new Size(0x3f, 20);
			this.ledTriksToolStripMenuItem.Text = "LedTriks";
			this.boardLayoutToolStripMenuItem.Name = "boardLayoutToolStripMenuItem";
			this.boardLayoutToolStripMenuItem.Size = new Size(0xe0, 22);
			this.boardLayoutToolStripMenuItem.Text = "Board layout";
			this.boardLayoutToolStripMenuItem.Click += new EventHandler(this.boardLayoutToolStripMenuItem_Click);
			this.cellSizeToolStripMenuItem.DropDownItems.AddRange(new ToolStripItem[] { this.toolStripMenuItem10, this.toolStripMenuItem11, this.toolStripMenuItem12, this.toolStripMenuItem13 });
			this.cellSizeToolStripMenuItem.Name = "cellSizeToolStripMenuItem";
			this.cellSizeToolStripMenuItem.Size = new Size(0xe0, 22);
			this.cellSizeToolStripMenuItem.Text = "Cell size";
			this.toolStripMenuItem10.Name = "toolStripMenuItem10";
			this.toolStripMenuItem10.Size = new Size(0x56, 22);
			this.toolStripMenuItem10.Text = "3";
			this.toolStripMenuItem10.Click += new EventHandler(this.toolStripMenuItem10_Click);
			this.toolStripMenuItem11.Checked = true;
			this.toolStripMenuItem11.CheckState = CheckState.Checked;
			this.toolStripMenuItem11.Name = "toolStripMenuItem11";
			this.toolStripMenuItem11.Size = new Size(0x56, 22);
			this.toolStripMenuItem11.Text = "5";
			this.toolStripMenuItem11.Click += new EventHandler(this.toolStripMenuItem10_Click);
			this.toolStripMenuItem12.Name = "toolStripMenuItem12";
			this.toolStripMenuItem12.Size = new Size(0x56, 22);
			this.toolStripMenuItem12.Text = "7";
			this.toolStripMenuItem12.Click += new EventHandler(this.toolStripMenuItem10_Click);
			this.toolStripMenuItem13.Name = "toolStripMenuItem13";
			this.toolStripMenuItem13.Size = new Size(0x56, 22);
			this.toolStripMenuItem13.Text = "10";
			this.toolStripMenuItem13.Click += new EventHandler(this.toolStripMenuItem10_Click);
			this.defaultFrameLengthToolStripMenuItem.DropDownItems.AddRange(new ToolStripItem[] { this.toolStripTextBoxFrameLength });
			this.defaultFrameLengthToolStripMenuItem.Name = "defaultFrameLengthToolStripMenuItem";
			this.defaultFrameLengthToolStripMenuItem.Size = new Size(0xe0, 22);
			this.defaultFrameLengthToolStripMenuItem.Text = "Default frame length";
			this.toolStripTextBoxFrameLength.Name = "toolStripTextBoxFrameLength";
			this.toolStripTextBoxFrameLength.Size = new Size(50, 23);
			this.toolStripTextBoxFrameLength.KeyPress += new KeyPressEventHandler(this.toolStripTextBoxFrameLength_KeyPress);
			this.toolStripMenuItem1.Name = "toolStripMenuItem1";
			this.toolStripMenuItem1.Size = new Size(0xdd, 6);
			this.ignoreFontDescentToolStripMenuItem.CheckOnClick = true;
			this.ignoreFontDescentToolStripMenuItem.Name = "ignoreFontDescentToolStripMenuItem";
			this.ignoreFontDescentToolStripMenuItem.Size = new Size(0xe0, 22);
			this.ignoreFontDescentToolStripMenuItem.Text = "Ignore font descent";
			this.confirmOnFrameRemoveToolStripMenuItem.Checked = true;
			this.confirmOnFrameRemoveToolStripMenuItem.CheckOnClick = true;
			this.confirmOnFrameRemoveToolStripMenuItem.CheckState = CheckState.Checked;
			this.confirmOnFrameRemoveToolStripMenuItem.Name = "confirmOnFrameRemoveToolStripMenuItem";
			this.confirmOnFrameRemoveToolStripMenuItem.Size = new Size(0xe0, 22);
			this.confirmOnFrameRemoveToolStripMenuItem.Text = "Confirm on frame remove";
			this.ghostThePreviousFrameToolStripMenuItem.Checked = true;
			this.ghostThePreviousFrameToolStripMenuItem.CheckOnClick = true;
			this.ghostThePreviousFrameToolStripMenuItem.CheckState = CheckState.Checked;
			this.ghostThePreviousFrameToolStripMenuItem.Name = "ghostThePreviousFrameToolStripMenuItem";
			this.ghostThePreviousFrameToolStripMenuItem.Size = new Size(0xe0, 22);
			this.ghostThePreviousFrameToolStripMenuItem.Text = "Ghost the previous frame";
			this.ghostThePreviousFrameToolStripMenuItem.Click += new EventHandler(this.ghostThePreviousFrameToolStripMenuItem_Click);
			this.autoresetAutoTextDefaultsToolStripMenuItem.CheckOnClick = true;
			this.autoresetAutoTextDefaultsToolStripMenuItem.Name = "autoresetAutoTextDefaultsToolStripMenuItem";
			this.autoresetAutoTextDefaultsToolStripMenuItem.Size = new Size(0xe0, 22);
			this.autoresetAutoTextDefaultsToolStripMenuItem.Text = "Auto-reset auto text defaults";
			this.toolStripMenuItem5.Name = "toolStripMenuItem5";
			this.toolStripMenuItem5.Size = new Size(0xdd, 6);
			this.copyThisFrameToolStripMenuItem.Name = "copyThisFrameToolStripMenuItem";
			this.copyThisFrameToolStripMenuItem.ShortcutKeys = Keys.Control | Keys.C;
			this.copyThisFrameToolStripMenuItem.Size = new Size(0xe0, 22);
			this.copyThisFrameToolStripMenuItem.Text = "Copy this frame";
			this.copyThisFrameToolStripMenuItem.Click += new EventHandler(this.copyThisFrameToolStripMenuItem_Click);
			this.pasteToolStripMenuItem.Name = "pasteToolStripMenuItem";
			this.pasteToolStripMenuItem.ShortcutKeys = Keys.Control | Keys.V;
			this.pasteToolStripMenuItem.Size = new Size(0xe0, 22);
			this.pasteToolStripMenuItem.Text = "Paste";
			this.pasteToolStripMenuItem.Click += new EventHandler(this.pasteToolStripMenuItem_Click);
			this.toolStripMenuItem7.Name = "toolStripMenuItem7";
			this.toolStripMenuItem7.Size = new Size(0xdd, 6);
			this.attachedPluginsToolStripMenuItem.Name = "attachedPluginsToolStripMenuItem";
			this.attachedPluginsToolStripMenuItem.Size = new Size(0xe0, 22);
			this.attachedPluginsToolStripMenuItem.Text = "Attached plugins";
			this.attachedPluginsToolStripMenuItem.Click += new EventHandler(this.attachedPluginsToolStripMenuItem_Click);
			this.playControlButtonsToolStripMenuItem.DropDownItems.AddRange(new ToolStripItem[] { this.previewToolStripMenuItem, this.executeToolStripMenuItem });
			this.playControlButtonsToolStripMenuItem.Name = "playControlButtonsToolStripMenuItem";
			this.playControlButtonsToolStripMenuItem.Size = new Size(0xe0, 22);
			this.playControlButtonsToolStripMenuItem.Text = "Play control buttons";
			this.previewToolStripMenuItem.Checked = true;
			this.previewToolStripMenuItem.CheckState = CheckState.Checked;
			this.previewToolStripMenuItem.Name = "previewToolStripMenuItem";
			this.previewToolStripMenuItem.Size = new Size(0x73, 22);
			this.previewToolStripMenuItem.Text = "Preview";
			this.previewToolStripMenuItem.Click += new EventHandler(this.previewToolStripMenuItem_Click);
			this.executeToolStripMenuItem.Name = "executeToolStripMenuItem";
			this.executeToolStripMenuItem.Size = new Size(0x73, 22);
			this.executeToolStripMenuItem.Text = "Execute";
			this.executeToolStripMenuItem.Click += new EventHandler(this.executeToolStripMenuItem_Click);
			this.panel.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Bottom | AnchorStyles.Top;
			this.panel.Controls.Add(this.checkBoxLoop);
			this.panel.Controls.Add(this.groupBoxCurrentFrame);
			this.panel.Controls.Add(this.groupBoxAutoText);
			this.panel.Controls.Add(this.buttonOrganize);
			this.panel.Controls.Add(this.labelLength);
			this.panel.Controls.Add(this.label1);
			this.panel.Controls.Add(this.groupBoxDisplay);
			this.panel.Controls.Add(this.groupBoxPreviewControl);
			this.panel.Location = new Point(11, 12);
			this.panel.Name = "panel";
			this.panel.Size = new Size(0x301, 0x219);
			this.panel.TabIndex = 0;
			this.checkBoxLoop.AutoSize = true;
			this.checkBoxLoop.Location = new Point(0x167, 50);
			this.checkBoxLoop.Name = "checkBoxLoop";
			this.checkBoxLoop.Size = new Size(50, 0x11);
			this.checkBoxLoop.TabIndex = 15;
			this.checkBoxLoop.Text = "Loop";
			this.checkBoxLoop.UseVisualStyleBackColor = true;
			this.checkBoxLoop.CheckedChanged += new EventHandler(this.checkBoxLoop_CheckedChanged);
			this.groupBoxCurrentFrame.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Bottom;
			this.groupBoxCurrentFrame.Controls.Add(this.buttonClone);
			this.groupBoxCurrentFrame.Controls.Add(this.label2);
			this.groupBoxCurrentFrame.Controls.Add(this.textBoxFrameLength);
			this.groupBoxCurrentFrame.Controls.Add(this.label3);
			this.groupBoxCurrentFrame.Controls.Add(this.buttonSaveFrame);
			this.groupBoxCurrentFrame.Controls.Add(this.buttonSaveAndCreateNew);
			this.groupBoxCurrentFrame.Controls.Add(this.pictureBoxShiftUp);
			this.groupBoxCurrentFrame.Controls.Add(this.buttonClear);
			this.groupBoxCurrentFrame.Controls.Add(this.pictureBoxShiftDown);
			this.groupBoxCurrentFrame.Controls.Add(this.pictureBoxShiftLeft);
			this.groupBoxCurrentFrame.Controls.Add(this.pictureBoxShiftRight);
			this.groupBoxCurrentFrame.Location = new Point(0x13, 0x128);
			this.groupBoxCurrentFrame.Name = "groupBoxCurrentFrame";
			this.groupBoxCurrentFrame.Size = new Size(730, 0x69);
			this.groupBoxCurrentFrame.TabIndex = 2;
			this.groupBoxCurrentFrame.TabStop = false;
			this.groupBoxCurrentFrame.Text = "Current Frame";
			this.buttonClone.Location = new Point(0x7f, 0x47);
			this.buttonClone.Name = "buttonClone";
			this.buttonClone.Size = new Size(0x6f, 23);
			this.buttonClone.TabIndex = 6;
			this.buttonClone.Text = "Clone this frame";
			this.buttonClone.UseVisualStyleBackColor = true;
			this.buttonClone.Click += new EventHandler(this.buttonClone_Click);
			this.label2.AutoSize = true;
			this.label2.Location = new Point(15, 20);
			this.label2.Name = "label2";
			this.label2.Size = new Size(0x6b, 13);
			this.label2.TabIndex = 0;
			this.label2.Text = "This frame will last for";
			this.textBoxFrameLength.Location = new Point(0x80, 0x11);
			this.textBoxFrameLength.Name = "textBoxFrameLength";
			this.textBoxFrameLength.Size = new Size(0x29, 20);
			this.textBoxFrameLength.TabIndex = 1;
			this.label3.AutoSize = true;
			this.label3.Location = new Point(0xaf, 20);
			this.label3.Name = "label3";
			this.label3.Size = new Size(0x3f, 13);
			this.label3.TabIndex = 2;
			this.label3.Text = "milliseconds";
			this.buttonSaveFrame.Location = new Point(0x12, 0x2a);
			this.buttonSaveFrame.Name = "buttonSaveFrame";
			this.buttonSaveFrame.Size = new Size(0x67, 23);
			this.buttonSaveFrame.TabIndex = 3;
			this.buttonSaveFrame.Text = "Save this frame";
			this.buttonSaveFrame.UseVisualStyleBackColor = true;
			this.buttonSaveFrame.Click += new EventHandler(this.buttonSaveFrame_Click);
			this.buttonSaveAndCreateNew.Location = new Point(0x7f, 0x2a);
			this.buttonSaveAndCreateNew.Name = "buttonSaveAndCreateNew";
			this.buttonSaveAndCreateNew.Size = new Size(0x97, 23);
			this.buttonSaveAndCreateNew.TabIndex = 4;
			this.buttonSaveAndCreateNew.Text = "Save and create new frame";
			this.buttonSaveAndCreateNew.UseVisualStyleBackColor = true;
			this.buttonSaveAndCreateNew.Click += new EventHandler(this.buttonSaveAndCreateNew_Click);
			this.pictureBoxShiftUp.Location = new Point(0x16d, 26);
			this.pictureBoxShiftUp.Name = "pictureBoxShiftUp";
			this.pictureBoxShiftUp.Size = new Size(24, 24);
			this.pictureBoxShiftUp.TabIndex = 2;
			this.pictureBoxShiftUp.TabStop = false;
			this.toolTip.SetToolTip(this.pictureBoxShiftUp, "Shift frame up");
			this.pictureBoxShiftUp.DoubleClick += new EventHandler(this.pictureBoxShiftUp_DoubleClick);
			this.pictureBoxShiftUp.Click += new EventHandler(this.pictureBoxShiftUp_Click);
			this.buttonClear.Location = new Point(0x12, 0x47);
			this.buttonClear.Name = "buttonClear";
			this.buttonClear.Size = new Size(0x4b, 23);
			this.buttonClear.TabIndex = 5;
			this.buttonClear.Text = "Clear frame";
			this.buttonClear.UseVisualStyleBackColor = true;
			this.buttonClear.Click += new EventHandler(this.buttonClear_Click);
			this.pictureBoxShiftDown.Location = new Point(0x16d, 0x3b);
			this.pictureBoxShiftDown.Name = "pictureBoxShiftDown";
			this.pictureBoxShiftDown.Size = new Size(24, 24);
			this.pictureBoxShiftDown.TabIndex = 3;
			this.pictureBoxShiftDown.TabStop = false;
			this.toolTip.SetToolTip(this.pictureBoxShiftDown, "Shift frame down");
			this.pictureBoxShiftDown.DoubleClick += new EventHandler(this.pictureBoxShiftDown_DoubleClick);
			this.pictureBoxShiftDown.Click += new EventHandler(this.pictureBoxShiftDown_Click);
			this.pictureBoxShiftLeft.Location = new Point(0x14f, 0x2a);
			this.pictureBoxShiftLeft.Name = "pictureBoxShiftLeft";
			this.pictureBoxShiftLeft.Size = new Size(24, 24);
			this.pictureBoxShiftLeft.TabIndex = 4;
			this.pictureBoxShiftLeft.TabStop = false;
			this.toolTip.SetToolTip(this.pictureBoxShiftLeft, "Shift frame left");
			this.pictureBoxShiftLeft.DoubleClick += new EventHandler(this.pictureBoxShiftLeft_DoubleClick);
			this.pictureBoxShiftLeft.Click += new EventHandler(this.pictureBoxShiftLeft_Click);
			this.pictureBoxShiftRight.Location = new Point(0x18b, 0x2a);
			this.pictureBoxShiftRight.Name = "pictureBoxShiftRight";
			this.pictureBoxShiftRight.Size = new Size(24, 24);
			this.pictureBoxShiftRight.TabIndex = 5;
			this.pictureBoxShiftRight.TabStop = false;
			this.toolTip.SetToolTip(this.pictureBoxShiftRight, "Shift frame right");
			this.pictureBoxShiftRight.DoubleClick += new EventHandler(this.pictureBoxShiftRight_DoubleClick);
			this.pictureBoxShiftRight.Click += new EventHandler(this.pictureBoxShiftRight_Click);
			this.groupBoxAutoText.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Bottom;
			this.groupBoxAutoText.Controls.Add(this.linkLabelMoreOptions);
			this.groupBoxAutoText.Controls.Add(this.buttonCreateAutoText);
			this.groupBoxAutoText.Controls.Add(this.textBoxAutoText);
			this.groupBoxAutoText.Controls.Add(this.labelFontName);
			this.groupBoxAutoText.Controls.Add(this.buttonFont);
			this.groupBoxAutoText.Location = new Point(0x13, 0x1a3);
			this.groupBoxAutoText.Name = "groupBoxAutoText";
			this.groupBoxAutoText.Size = new Size(730, 100);
			this.groupBoxAutoText.TabIndex = 3;
			this.groupBoxAutoText.TabStop = false;
			this.groupBoxAutoText.Text = "Auto Text";
			this.linkLabelMoreOptions.AutoSize = true;
			this.linkLabelMoreOptions.Location = new Point(8, 0x4a);
			this.linkLabelMoreOptions.Name = "linkLabelMoreOptions";
			this.linkLabelMoreOptions.Size = new Size(70, 13);
			this.linkLabelMoreOptions.TabIndex = 4;
			this.linkLabelMoreOptions.TabStop = true;
			this.linkLabelMoreOptions.Text = "More Options";
			this.linkLabelMoreOptions.VisitedLinkColor = Color.Blue;
			this.linkLabelMoreOptions.LinkClicked += new LinkLabelLinkClickedEventHandler(this.linkLabelMoreOptions_LinkClicked);
			this.buttonCreateAutoText.Anchor = AnchorStyles.Right | AnchorStyles.Top;
			this.buttonCreateAutoText.Location = new Point(0x289, 0x31);
			this.buttonCreateAutoText.Name = "buttonCreateAutoText";
			this.buttonCreateAutoText.Size = new Size(0x4b, 23);
			this.buttonCreateAutoText.TabIndex = 3;
			this.buttonCreateAutoText.Text = "Create";
			this.buttonCreateAutoText.UseVisualStyleBackColor = true;
			this.buttonCreateAutoText.Click += new EventHandler(this.buttonCreateAutoText_Click);
			this.textBoxAutoText.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Top;
			this.textBoxAutoText.Location = new Point(11, 0x33);
			this.textBoxAutoText.Name = "textBoxAutoText";
			this.textBoxAutoText.Size = new Size(0x26e, 20);
			this.textBoxAutoText.TabIndex = 2;
			this.textBoxAutoText.Enter += new EventHandler(this.textBoxAutoText_Enter);
			this.textBoxAutoText.Leave += new EventHandler(this.textBoxAutoText_Leave);
			this.labelFontName.AutoSize = true;
			this.labelFontName.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
			this.labelFontName.Location = new Point(0x5c, 27);
			this.labelFontName.Name = "labelFontName";
			this.labelFontName.Size = new Size(0x79, 13);
			this.labelFontName.TabIndex = 1;
			this.labelFontName.Text = "Microsoft Sans Serif";
			this.buttonFont.Location = new Point(11, 22);
			this.buttonFont.Name = "buttonFont";
			this.buttonFont.Size = new Size(0x4b, 23);
			this.buttonFont.TabIndex = 0;
			this.buttonFont.Text = "Font";
			this.buttonFont.UseVisualStyleBackColor = true;
			this.buttonFont.Click += new EventHandler(this.buttonFont_Click);
			this.buttonOrganize.Anchor = AnchorStyles.Right | AnchorStyles.Top;
			this.buttonOrganize.Location = new Point(0x29f, 5);
			this.buttonOrganize.Name = "buttonOrganize";
			this.buttonOrganize.Size = new Size(0x5f, 23);
			this.buttonOrganize.TabIndex = 14;
			this.buttonOrganize.Text = "Organize frames";
			this.buttonOrganize.UseVisualStyleBackColor = true;
			this.buttonOrganize.Click += new EventHandler(this.buttonOrganize_Click);
			this.labelLength.Anchor = AnchorStyles.Right | AnchorStyles.Top;
			this.labelLength.AutoSize = true;
			this.labelLength.Location = new Point(0x2b6, 0x33);
			this.labelLength.Name = "labelLength";
			this.labelLength.Size = new Size(0x2b, 13);
			this.labelLength.TabIndex = 7;
			this.labelLength.Text = "0:0.000";
			this.label1.Anchor = AnchorStyles.Right | AnchorStyles.Top;
			this.label1.AutoSize = true;
			this.label1.Location = new Point(0x248, 0x33);
			this.label1.Name = "label1";
			this.label1.Size = new Size(0x68, 13);
			this.label1.TabIndex = 6;
			this.label1.Text = "Total running length:";
			this.groupBoxDisplay.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Bottom | AnchorStyles.Top;
			this.groupBoxDisplay.Controls.Add(this.panel1);
			this.groupBoxDisplay.Controls.Add(this.buttonNext);
			this.groupBoxDisplay.Controls.Add(this.labelPosition);
			this.groupBoxDisplay.Controls.Add(this.buttonPrevious);
			this.groupBoxDisplay.Controls.Add(this.labelCurrentFrame);
			this.groupBoxDisplay.Controls.Add(this.buttonRemoveAll);
			this.groupBoxDisplay.Controls.Add(this.buttonRemove);
			this.groupBoxDisplay.Controls.Add(this.trackBarFrame);
			this.groupBoxDisplay.Location = new Point(0x13, 0x43);
			this.groupBoxDisplay.Name = "groupBoxDisplay";
			this.groupBoxDisplay.Size = new Size(730, 0xce);
			this.groupBoxDisplay.TabIndex = 1;
			this.groupBoxDisplay.TabStop = false;
			this.panel1.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Bottom | AnchorStyles.Top;
			this.panel1.AutoScroll = true;
			this.panel1.Controls.Add(this.pictureBoxPreview);
			this.panel1.Location = new Point(5, 0x2c);
			this.panel1.Name = "panel1";
			this.panel1.Size = new Size(720, 80);
			this.panel1.TabIndex = 0x11;
			this.pictureBoxPreview.Location = new Point(0, 0);
			this.pictureBoxPreview.Name = "pictureBoxPreview";
			this.pictureBoxPreview.Size = new Size(720, 80);
			this.pictureBoxPreview.TabIndex = 0;
			this.pictureBoxPreview.TabStop = false;
			this.pictureBoxPreview.MouseDown += new MouseEventHandler(this.pictureBoxPreview_MouseDown);
			this.pictureBoxPreview.MouseMove += new MouseEventHandler(this.pictureBoxPreview_MouseMove);
			this.pictureBoxPreview.Paint += new PaintEventHandler(this.pictureBoxPreview_Paint);
			this.pictureBoxPreview.MouseUp += new MouseEventHandler(this.pictureBoxPreview_MouseUp);
			this.buttonNext.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
			this.buttonNext.Location = new Point(40, 0xb1);
			this.buttonNext.Name = "buttonNext";
			this.buttonNext.Size = new Size(23, 23);
			this.buttonNext.TabIndex = 3;
			this.buttonNext.Text = ">";
			this.toolTip.SetToolTip(this.buttonNext, "Next frame");
			this.buttonNext.UseVisualStyleBackColor = true;
			this.buttonNext.Click += new EventHandler(this.buttonNext_Click);
			this.labelPosition.AutoSize = true;
			this.labelPosition.Location = new Point(6, 0x10);
			this.labelPosition.Name = "labelPosition";
			this.labelPosition.Size = new Size(25, 13);
			this.labelPosition.TabIndex = 0x10;
			this.labelPosition.Text = "0, 0";
			this.buttonPrevious.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
			this.buttonPrevious.Location = new Point(11, 0xb1);
			this.buttonPrevious.Name = "buttonPrevious";
			this.buttonPrevious.Size = new Size(23, 23);
			this.buttonPrevious.TabIndex = 2;
			this.buttonPrevious.Text = "<";
			this.toolTip.SetToolTip(this.buttonPrevious, "Previous frame");
			this.buttonPrevious.UseVisualStyleBackColor = true;
			this.buttonPrevious.Click += new EventHandler(this.buttonPrevious_Click);
			this.labelCurrentFrame.AutoSize = true;
			this.labelCurrentFrame.ForeColor = Color.Blue;
			this.labelCurrentFrame.Location = new Point(8, 0);
			this.labelCurrentFrame.Name = "labelCurrentFrame";
			this.labelCurrentFrame.Size = new Size(0x42, 13);
			this.labelCurrentFrame.TabIndex = 0;
			this.labelCurrentFrame.Text = "Frame 0 of 0";
			this.buttonRemoveAll.Anchor = AnchorStyles.Right | AnchorStyles.Bottom;
			this.buttonRemoveAll.Location = new Point(0x289, 0xb1);
			this.buttonRemoveAll.Name = "buttonRemoveAll";
			this.buttonRemoveAll.Size = new Size(0x4b, 23);
			this.buttonRemoveAll.TabIndex = 5;
			this.buttonRemoveAll.Text = "Remove all";
			this.buttonRemoveAll.UseVisualStyleBackColor = true;
			this.buttonRemoveAll.Click += new EventHandler(this.buttonRemoveAll_Click);
			this.buttonRemove.Anchor = AnchorStyles.Right | AnchorStyles.Bottom;
			this.buttonRemove.Location = new Point(0x238, 0xb1);
			this.buttonRemove.Name = "buttonRemove";
			this.buttonRemove.Size = new Size(0x4b, 23);
			this.buttonRemove.TabIndex = 4;
			this.buttonRemove.Text = "Remove";
			this.buttonRemove.UseVisualStyleBackColor = true;
			this.buttonRemove.Click += new EventHandler(this.buttonRemove_Click);
			this.trackBarFrame.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Bottom;
			this.trackBarFrame.Location = new Point(6, 130);
			this.trackBarFrame.Maximum = 1;
			this.trackBarFrame.Minimum = 1;
			this.trackBarFrame.Name = "trackBarFrame";
			this.trackBarFrame.Size = new Size(0x2ce, 0x2d);
			this.trackBarFrame.TabIndex = 1;
			this.trackBarFrame.TickStyle = TickStyle.TopLeft;
			this.trackBarFrame.Value = 1;
			this.trackBarFrame.Scroll += new EventHandler(this.trackBarFrame_Scroll);
			this.groupBoxPreviewControl.Controls.Add(this.pictureBoxStop);
			this.groupBoxPreviewControl.Controls.Add(this.pictureBoxPlayFromBeginning);
			this.groupBoxPreviewControl.Controls.Add(this.pictureBoxPlay);
			this.groupBoxPreviewControl.Location = new Point(0x150, 5);
			this.groupBoxPreviewControl.Name = "groupBoxPreviewControl";
			this.groupBoxPreviewControl.Size = new Size(0x60, 40);
			this.groupBoxPreviewControl.TabIndex = 0;
			this.groupBoxPreviewControl.TabStop = false;
			this.pictureBoxStop.Location = new Point(0x42, 12);
			this.pictureBoxStop.Name = "pictureBoxStop";
			this.pictureBoxStop.Size = new Size(24, 24);
			this.pictureBoxStop.TabIndex = 2;
			this.pictureBoxStop.TabStop = false;
			this.toolTip.SetToolTip(this.pictureBoxStop, "Stop");
			this.pictureBoxStop.Click += new EventHandler(this.pictureBoxStop_Click);
			this.pictureBoxPlayFromBeginning.Location = new Point(0x24, 12);
			this.pictureBoxPlayFromBeginning.Name = "pictureBoxPlayFromBeginning";
			this.pictureBoxPlayFromBeginning.Size = new Size(24, 24);
			this.pictureBoxPlayFromBeginning.TabIndex = 1;
			this.pictureBoxPlayFromBeginning.TabStop = false;
			this.toolTip.SetToolTip(this.pictureBoxPlayFromBeginning, "Start at the first frame");
			this.pictureBoxPlayFromBeginning.Click += new EventHandler(this.pictureBoxPlayFromBeginning_Click);
			this.pictureBoxPlay.Location = new Point(6, 12);
			this.pictureBoxPlay.Name = "pictureBoxPlay";
			this.pictureBoxPlay.Size = new Size(24, 24);
			this.pictureBoxPlay.TabIndex = 0;
			this.pictureBoxPlay.TabStop = false;
			this.toolTip.SetToolTip(this.pictureBoxPlay, "Start at the current frame");
			this.pictureBoxPlay.Click += new EventHandler(this.pictureBoxPlay_Click);
			this.toolTip.UseAnimation = false;
			this.toolTip.UseFading = false;
			this.fontDialog.AllowSimulations = false;
			this.fontDialog.Font = new Font("Microsoft Sans Serif", 10f);
			this.fontDialog.FontMustExist = true;
			this.fontDialog.MaxSize = 10;
			this.fontDialog.MinSize = 10;
			this.fontDialog.ShowEffects = false;
			this.saveFileDialog.Title = "Save As";
			base.AutoScaleDimensions = new SizeF(6f, 13f);
			base.ClientSize = new Size(0x318, 0x22f);
			base.Controls.Add(this.panel);
			base.Controls.Add(this.menuStrip);
			base.KeyPreview = true;
			base.MainMenuStrip = this.menuStrip;
			this.MinimumSize = new Size(800, 0x251);
			base.Name = "LedTriks";
			base.StartPosition = FormStartPosition.CenterScreen;
			base.ResizeBegin += new EventHandler(this.LedTriks_ResizeBegin);
			base.Resize += new EventHandler(this.LedTriks_Resize);
			base.KeyPress += new KeyPressEventHandler(this.LedTriks_KeyPress);
			base.FormClosing += new FormClosingEventHandler(this.LedTriks_FormClosing);
			base.ResizeEnd += new EventHandler(this.LedTriks_ResizeEnd);
			base.Load += new EventHandler(this.LedTriks_Load);
			this.menuStrip.ResumeLayout(false);
			this.menuStrip.PerformLayout();
			this.panel.ResumeLayout(false);
			this.panel.PerformLayout();
			this.groupBoxCurrentFrame.ResumeLayout(false);
			this.groupBoxCurrentFrame.PerformLayout();
			((ISupportInitialize) this.pictureBoxShiftUp).EndInit();
			((ISupportInitialize) this.pictureBoxShiftDown).EndInit();
			((ISupportInitialize) this.pictureBoxShiftLeft).EndInit();
			((ISupportInitialize) this.pictureBoxShiftRight).EndInit();
			this.groupBoxAutoText.ResumeLayout(false);
			this.groupBoxAutoText.PerformLayout();
			this.groupBoxDisplay.ResumeLayout(false);
			this.groupBoxDisplay.PerformLayout();
			this.panel1.ResumeLayout(false);
			((ISupportInitialize) this.pictureBoxPreview).EndInit();
			this.trackBarFrame.EndInit();
			this.groupBoxPreviewControl.ResumeLayout(false);
			((ISupportInitialize) this.pictureBoxStop).EndInit();
			((ISupportInitialize) this.pictureBoxPlayFromBeginning).EndInit();
			((ISupportInitialize) this.pictureBoxPlay).EndInit();
			base.ResumeLayout(false);
			base.PerformLayout();
		}
		#endregion

		protected override void Dispose(bool disposing)
		{
			if (this.m_generator != null)
			{
				this.m_generator.Dispose();
			}
			base.Dispose(disposing);
			GC.SuppressFinalize(this);
		}
	}
}
