//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Controllers.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("Controllers.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected baud rate might not be supported by your hardware..
        /// </summary>
        internal static string HighBaudRateSupport {
            get {
                return ResourceManager.GetString("HighBaudRateSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Baud rate has not been selected..
        /// </summary>
        internal static string Serial_BaudError {
            get {
                return ResourceManager.GetString("Serial_BaudError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Invalid numeric value for data bits..
        /// </summary>
        internal static string Serial_DataBitsError {
            get {
                return ResourceManager.GetString("Serial_DataBitsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Parity has not been selected..
        /// </summary>
        internal static string Serial_ParityError {
            get {
                return ResourceManager.GetString("Serial_ParityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Port name has not been selected..
        /// </summary>
        internal static string Serial_PortError {
            get {
                return ResourceManager.GetString("Serial_PortError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following items need to be resolved:
        ///
        ///.
        /// </summary>
        internal static string Serial_Resolve {
            get {
                return ResourceManager.GetString("Serial_Resolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Stop bits have not been selected..
        /// </summary>
        internal static string Serial_StopBitsError {
            get {
                return ResourceManager.GetString("Serial_StopBitsError", resourceCulture);
            }
        }
    }
}
