//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Controllers.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlugInsCommon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected baud rate might not be supported by your hardware..
        /// </summary>
        internal static string HighBaudRateSupport {
            get {
                return ResourceManager.GetString("HighBaudRateSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Baud rate has not been selected..
        /// </summary>
        internal static string Serial_BaudError {
            get {
                return ResourceManager.GetString("Serial_BaudError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Invalid numeric value for data bits..
        /// </summary>
        internal static string Serial_DataBitsError {
            get {
                return ResourceManager.GetString("Serial_DataBitsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Parity has not been selected..
        /// </summary>
        internal static string Serial_ParityError {
            get {
                return ResourceManager.GetString("Serial_ParityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Port name has not been selected..
        /// </summary>
        internal static string Serial_PortError {
            get {
                return ResourceManager.GetString("Serial_PortError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following items need to be resolved:
        ///
        ///.
        /// </summary>
        internal static string Serial_Resolve {
            get {
                return ResourceManager.GetString("Serial_Resolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Stop bits have not been selected..
        /// </summary>
        internal static string Serial_StopBitsError {
            get {
                return ResourceManager.GetString("Serial_StopBitsError", resourceCulture);
            }
        }
    }
}
