using System;
using System.Windows.Forms;
using System.Drawing;
using System.ComponentModel;
using System.Collections;

namespace WattMeter {
    internal partial class WattMeterDialog {
        private IContainer components = null;

        #region Windows Form Designer generated code
        private Button buttonCalcTotalDraw;
        private Button buttonClearChecks;
        private Button buttonCreateGroup;
        private Button buttonDone;
        private Button buttonRenameGroup;
        private Button buttonTestGroup;
        private Button buttonUpdateGroup;
        private CheckedListBox checkedListBoxChannels;
        private GroupBox groupBox1;
        private GroupBox groupBox2;
        private GroupBox groupBox3;
        private HScrollBar hScrollBar;
        private Label label1;
        private Label label2;
        private Label label3;
        private Label label4;
        private Label label5;
        private ListBox listBoxGroups;
        private PictureBox pictureBoxGraph;
        private TextBox textBoxChannelAmps;
        private TextBox textBoxChannelWatts;
        private TextBox textBoxMaxAmps;
        private TextBox textBoxVolts;

        private void InitializeComponent() {
            this.groupBox1 = new GroupBox();
            this.textBoxChannelAmps = new TextBox();
            this.label5 = new Label();
            this.buttonClearChecks = new Button();
            this.buttonUpdateGroup = new Button();
            this.textBoxChannelWatts = new TextBox();
            this.label2 = new Label();
            this.checkedListBoxChannels = new CheckedListBox();
            this.groupBox2 = new GroupBox();
            this.label4 = new Label();
            this.textBoxVolts = new TextBox();
            this.label3 = new Label();
            this.buttonTestGroup = new Button();
            this.textBoxMaxAmps = new TextBox();
            this.label1 = new Label();
            this.buttonRenameGroup = new Button();
            this.buttonCreateGroup = new Button();
            this.listBoxGroups = new ListBox();
            this.groupBox3 = new GroupBox();
            this.hScrollBar = new HScrollBar();
            this.pictureBoxGraph = new PictureBox();
            this.buttonCalcTotalDraw = new Button();
            this.buttonDone = new Button();
            this.groupBox1.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.groupBox3.SuspendLayout();
            ((ISupportInitialize)this.pictureBoxGraph).BeginInit();
            base.SuspendLayout();
            this.groupBox1.Controls.Add(this.textBoxChannelAmps);
            this.groupBox1.Controls.Add(this.label5);
            this.groupBox1.Controls.Add(this.buttonClearChecks);
            this.groupBox1.Controls.Add(this.buttonUpdateGroup);
            this.groupBox1.Controls.Add(this.textBoxChannelWatts);
            this.groupBox1.Controls.Add(this.label2);
            this.groupBox1.Controls.Add(this.checkedListBoxChannels);
            this.groupBox1.Location = new Point(30, 13);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(0xe1, 310);
            this.groupBox1.TabIndex = 0;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Channels";
            this.textBoxChannelAmps.Location = new Point(0xb5, 0xf5);
            this.textBoxChannelAmps.Name = "textBoxChannelAmps";
            this.textBoxChannelAmps.Size = new Size(0x21, 20);
            this.textBoxChannelAmps.TabIndex = 5;
            this.textBoxChannelAmps.Leave += new EventHandler(this.textBoxChannelAmps_Leave);
            this.label5.AutoSize = true;
            this.label5.Location = new Point(0x83, 0xf8);
            this.label5.Name = "label5";
            this.label5.Size = new Size(0x2c, 13);
            this.label5.TabIndex = 4;
            this.label5.Text = "or amps";
            this.buttonClearChecks.Location = new Point(8, 0xd3);
            this.buttonClearChecks.Name = "buttonClearChecks";
            this.buttonClearChecks.Size = new Size(0x59, 0x17);
            this.buttonClearChecks.TabIndex = 1;
            this.buttonClearChecks.Text = "Clear checks";
            this.buttonClearChecks.UseVisualStyleBackColor = true;
            this.buttonClearChecks.Click += new EventHandler(this.buttonClearChecks_Click);
            this.buttonUpdateGroup.Enabled = false;
            this.buttonUpdateGroup.Location = new Point(8, 0x114);
            this.buttonUpdateGroup.Name = "buttonUpdateGroup";
            this.buttonUpdateGroup.Size = new Size(0x59, 0x17);
            this.buttonUpdateGroup.TabIndex = 6;
            this.buttonUpdateGroup.Text = "Update Group";
            this.buttonUpdateGroup.UseVisualStyleBackColor = true;
            this.buttonUpdateGroup.Click += new EventHandler(this.buttonUpdateGroup_Click);
            this.textBoxChannelWatts.Location = new Point(0x55, 0xf5);
            this.textBoxChannelWatts.Name = "textBoxChannelWatts";
            this.textBoxChannelWatts.Size = new Size(40, 20);
            this.textBoxChannelWatts.TabIndex = 3;
            this.textBoxChannelWatts.Leave += new EventHandler(this.textBoxChannelWatts_Leave);
            this.label2.AutoSize = true;
            this.label2.Location = new Point(5, 0xf8);
            this.label2.Name = "label2";
            this.label2.Size = new Size(0x4a, 13);
            this.label2.TabIndex = 2;
            this.label2.Text = "Channel watts";
            this.checkedListBoxChannels.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Bottom | AnchorStyles.Top;
            this.checkedListBoxChannels.FormattingEnabled = true;
            this.checkedListBoxChannels.Location = new Point(8, 0x15);
            this.checkedListBoxChannels.Name = "checkedListBoxChannels";
            this.checkedListBoxChannels.Size = new Size(0xce, 0xb8);
            this.checkedListBoxChannels.TabIndex = 0;
            this.checkedListBoxChannels.SelectedIndexChanged += new EventHandler(this.checkedListBoxChannels_SelectedIndexChanged);
            this.checkedListBoxChannels.ItemCheck += new ItemCheckEventHandler(this.checkedListBoxChannels_ItemCheck);
            this.groupBox2.Controls.Add(this.label4);
            this.groupBox2.Controls.Add(this.textBoxVolts);
            this.groupBox2.Controls.Add(this.label3);
            this.groupBox2.Controls.Add(this.buttonTestGroup);
            this.groupBox2.Controls.Add(this.textBoxMaxAmps);
            this.groupBox2.Controls.Add(this.label1);
            this.groupBox2.Controls.Add(this.buttonRenameGroup);
            this.groupBox2.Controls.Add(this.buttonCreateGroup);
            this.groupBox2.Controls.Add(this.listBoxGroups);
            this.groupBox2.Location = new Point(0x10f, 13);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new Size(0xdf, 310);
            this.groupBox2.TabIndex = 1;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "Groups";
            this.label4.AutoSize = true;
            this.label4.Location = new Point(0xa5, 0x119);
            this.label4.Name = "label4";
            this.label4.Size = new Size(0x1d, 13);
            this.label4.TabIndex = 8;
            this.label4.Text = "volts";
            this.textBoxVolts.Location = new Point(0x7e, 0x116);
            this.textBoxVolts.MaxLength = 3;
            this.textBoxVolts.Name = "textBoxVolts";
            this.textBoxVolts.Size = new Size(0x21, 20);
            this.textBoxVolts.TabIndex = 7;
            this.textBoxVolts.Leave += new EventHandler(this.textBoxVolts_Leave);
            this.label3.AutoSize = true;
            this.label3.Location = new Point(0x5e, 0x119);
            this.label3.Name = "label3";
            this.label3.Size = new Size(0x1a, 13);
            this.label3.TabIndex = 6;
            this.label3.Text = "with";
            this.buttonTestGroup.Enabled = false;
            this.buttonTestGroup.Location = new Point(13, 0x114);
            this.buttonTestGroup.Name = "buttonTestGroup";
            this.buttonTestGroup.Size = new Size(0x4b, 0x17);
            this.buttonTestGroup.TabIndex = 5;
            this.buttonTestGroup.Text = "Test Group";
            this.buttonTestGroup.UseVisualStyleBackColor = true;
            this.buttonTestGroup.Click += new EventHandler(this.buttonTestGroup_Click);
            this.textBoxMaxAmps.Enabled = false;
            this.textBoxMaxAmps.Location = new Point(0x47, 0xce);
            this.textBoxMaxAmps.Name = "textBoxMaxAmps";
            this.textBoxMaxAmps.Size = new Size(0x36, 20);
            this.textBoxMaxAmps.TabIndex = 2;
            this.textBoxMaxAmps.Leave += new EventHandler(this.textBoxMaxAmps_Leave);
            this.label1.AutoSize = true;
            this.label1.Location = new Point(10, 0xd1);
            this.label1.Name = "label1";
            this.label1.Size = new Size(0x37, 13);
            this.label1.TabIndex = 1;
            this.label1.Text = "Max amps";
            this.buttonRenameGroup.Enabled = false;
            this.buttonRenameGroup.Location = new Point(0x79, 0xf2);
            this.buttonRenameGroup.Name = "buttonRenameGroup";
            this.buttonRenameGroup.Size = new Size(90, 0x17);
            this.buttonRenameGroup.TabIndex = 4;
            this.buttonRenameGroup.Text = "Rename Group";
            this.buttonRenameGroup.UseVisualStyleBackColor = true;
            this.buttonRenameGroup.Click += new EventHandler(this.buttonRenameGroup_Click);
            this.buttonCreateGroup.Enabled = false;
            this.buttonCreateGroup.Location = new Point(13, 0xf2);
            this.buttonCreateGroup.Name = "buttonCreateGroup";
            this.buttonCreateGroup.Size = new Size(0x5c, 0x17);
            this.buttonCreateGroup.TabIndex = 3;
            this.buttonCreateGroup.Text = "Create Group";
            this.buttonCreateGroup.UseVisualStyleBackColor = true;
            this.buttonCreateGroup.Click += new EventHandler(this.buttonCreateGroup_Click);
            this.listBoxGroups.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Bottom | AnchorStyles.Top;
            this.listBoxGroups.FormattingEnabled = true;
            this.listBoxGroups.Location = new Point(12, 0x18);
            this.listBoxGroups.Name = "listBoxGroups";
            this.listBoxGroups.Size = new Size(0xc7, 0xad);
            this.listBoxGroups.TabIndex = 0;
            this.listBoxGroups.SelectedIndexChanged += new EventHandler(this.listBoxGroups_SelectedIndexChanged);
            this.listBoxGroups.KeyDown += new KeyEventHandler(this.listBoxGroups_KeyDown);
            this.groupBox3.Controls.Add(this.hScrollBar);
            this.groupBox3.Controls.Add(this.pictureBoxGraph);
            this.groupBox3.Controls.Add(this.buttonCalcTotalDraw);
            this.groupBox3.Location = new Point(30, 350);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new Size(0x1d0, 0xd5);
            this.groupBox3.TabIndex = 2;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "Sequence Total Current Draw";
            this.hScrollBar.Enabled = false;
            this.hScrollBar.Location = new Point(13, 0x99);
            this.hScrollBar.Name = "hScrollBar";
            this.hScrollBar.Size = new Size(0x1b6, 0x11);
            this.hScrollBar.TabIndex = 2;
            this.hScrollBar.ValueChanged += new EventHandler(this.hScrollBar_ValueChanged);
            this.pictureBoxGraph.BackColor = Color.White;
            this.pictureBoxGraph.Location = new Point(13, 0x1c);
            this.pictureBoxGraph.Name = "pictureBoxGraph";
            this.pictureBoxGraph.Size = new Size(0x1b6, 0x7d);
            this.pictureBoxGraph.TabIndex = 0;
            this.pictureBoxGraph.TabStop = false;
            this.pictureBoxGraph.Paint += new PaintEventHandler(this.pictureBoxGraph_Paint);
            this.buttonCalcTotalDraw.Location = new Point(13, 180);
            this.buttonCalcTotalDraw.Name = "buttonCalcTotalDraw";
            this.buttonCalcTotalDraw.Size = new Size(0x4b, 0x17);
            this.buttonCalcTotalDraw.TabIndex = 1;
            this.buttonCalcTotalDraw.Text = "Calculate";
            this.buttonCalcTotalDraw.UseVisualStyleBackColor = true;
            this.buttonCalcTotalDraw.Click += new EventHandler(this.buttonCalcTotalDraw_Click);
            this.buttonDone.Anchor = AnchorStyles.Right | AnchorStyles.Bottom;
            this.buttonDone.DialogResult = System.Windows.Forms.DialogResult.OK;
            this.buttonDone.Location = new Point(0x1bc, 570);
            this.buttonDone.Name = "buttonDone";
            this.buttonDone.Size = new Size(0x4b, 0x17);
            this.buttonDone.TabIndex = 3;
            this.buttonDone.Text = "Done";
            this.buttonDone.UseVisualStyleBackColor = true;
            this.buttonDone.Click += new EventHandler(this.buttonDone_Click);
            base.AutoScaleDimensions = new SizeF(6f, 13f);
            base.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            base.ClientSize = new Size(0x213, 0x25d);
            base.Controls.Add(this.buttonDone);
            base.Controls.Add(this.groupBox3);
            base.Controls.Add(this.groupBox2);
            base.Controls.Add(this.groupBox1);
            base.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            base.Name = "WattMeterDialog";
            base.StartPosition = FormStartPosition.CenterScreen;
            this.Text = "Watt Meter";
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            this.groupBox3.ResumeLayout(false);
            ((ISupportInitialize)this.pictureBoxGraph).EndInit();
            base.ResumeLayout(false);
        }
        #endregion

        protected override void Dispose(bool disposing) {
            if (disposing && (this.components != null)) {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}